apiVersion: v1
kind: Secret
metadata:
    name: gotosocial-s3-secret
    namespace: gotosocial
type: Opaque
stringData:
    s3_access_key: ENC[AES256_GCM,data:PcVIJ9mrMoy8SEn1kESOWGA8Gug=,iv:/PGjzYwzI6Xxk+SSJQCfvDm9A41CMS3nbFJ3KCGe4jI=,tag:YU1Slpgq6daQAf0ZAlI4dA==,type:str]
    s3_secret_key: ENC[AES256_GCM,data:3TR5AVF97WUEdAHJ1cmoWAXP9lybNGfAtZkTeSsQ/N2TeoXxbbJBHQ==,iv:MTHZo+A02mttNJE5Yq6mjnjGJTPwLc0OKD6Iq10wSPM=,tag:Tl4ykkAKWTfl87shiDN34g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1esjyg2qfy49awv0ptkzvpk425adczjr38m37w2mmcahzc4p8n54sll2nzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbHBuL29JZ0dZcnF4eDl2
            Z2gyNjdyTVdBQmVXK1hDRnBnZ3o1NlVKcEdNCnhQeDJMVUdkSHduSVFud2Z2QWpC
            WTBFM252cU84em9wUHFFelU3VHo3blUKLS0tIDRmNmJuS0daQXBVei9ickFteHFs
            WUxRWFBQUndDbTc5YlZocFRCMVB5V1kKZq9opTdGc68YuAhiqEpjQU9frnXOoJtJ
            Pjj0BksifkggpAFbKZUYqrqTK+RrUB3PkVyikWLSUfQ1CCuFkqAKDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T09:40:15Z"
    mac: ENC[AES256_GCM,data:KBpfZAnO0Qlq1lHM3COAGJWuomm2O+CEuifJX6U67iJnEodeSM1m+4Vo552H59IjQIuwL7mVYMyJiSMU1/zK743X/fV0+PFJ+al5bJ6KsaO8yjFyDAGtYtCxXVCcW44MJL/7OWcDg0pMdbt+uLzsAXTa6IXfulykQnMTIPtmeMw=,iv:k/0/AxjVjDaUK6t2vmeE6gdHsCGQT51c3y1MjOFxvlc=,tag:8UJTdPhufUwsMXPZ/wxmZA==,type:str]
    pgp: []
    encrypted_regex: ^(apiKey|appUserPassword|otelUserPassword|harborAdminPassword|totpVaultKey|kimaiAppSecret|kimaiAdminPassword|GITHUB_CLIENT_ID|GITHUB_CLIENT_SECRET|GITHUB_PRIVATE_KEY|woosh|root_password|rspamd_password|pgdb_password|matrix_access_token|pgdb_remote_url|hmac_secret_key|adminPassword|adminEmail|jenkinsAdminEmail|securityRealm|gerrit.config|routing_key|DATABASE_URL|SMTP_PASSWORD|SECRET_KEY_BASE|admin_password|extraCommands|key|clickhouseDatabaseURL|databaseURL|client_id|client_secret|secret_key_base|otp_secret|private_key|public_key|primaryKey|deterministicKey|keyDerivationSalt|token|clientId|secretKey|installationId|installationKey|uriOverride|adminToken.value|password.value|sql_password|erlangCookie|AUTHENTICATION_PASSWORD|ROOM_API_SECRET_KEY|adminPassword|configPassword|adminUser|configUser|MAIL_PASSWORD|APP_KEY|api_key|api_secret|keys|livekit_key|livekit_secret|secret_key|admin_pass|admin_email|mariadbPassword|mariadbRootPassword|privateKey|data|stringData|PASSWD|password|pass|postgresPassword|postgresqlPassword|redminePassword|smtpPassword|registration_shared_secret|shared_secret|secret|admin_token|integrationKey|integration_key|rootPassword|adminPassword|adminUser|adminEmail|emailPassword|secretKey|appId|clientSecret|webhookSecret)$
    version: 3.9.1
