apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gotosocial
  namespace: gotosocial
spec:
  resources:
    requests:
      storage: 512Mi
  storageClassName: longhorn-2replicas
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
