apiVersion: v1
kind: Secret
metadata:
    name: loki-s3-credentials
    namespace: loki
type: Opaque
stringData:
    access_key: ENC[AES256_GCM,data:gwTyR1GsgApjXGkjbjuUGA35CO0=,iv:7XbpfdtSNBsWfAs0lJ0EuNq1LMZkTfd9KtJmh591hVw=,tag:QhbbxRGB1VHiW2bXTtadEw==,type:str]
    secret_key: ENC[AES256_GCM,data:vXuOwuI2vc9UXVzmCE4LAQfYLLQDw60USSX6zNAjC6C4Xc9bdUQ8qA==,iv:yZBW57ZlleePqLm93bkb1YqBQvDKt9eD+g/7NNPzOYE=,tag:3jcpnbl/UGxUO2cNXoJJ1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1esjyg2qfy49awv0ptkzvpk425adczjr38m37w2mmcahzc4p8n54sll2nzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYOHg1NFQwNFhjU1dYUWJY
            R0o2SnN3OWZHYUtacXF3dHcxNnRFT2ZpbmtjCkFwQk5lM1U4NVBuOGVNYzVvUE5k
            TWU0TjZwTUUrdUxtZ3I0empEM1dOcG8KLS0tIEJma3ZraDRCd1BwU1czVWZYSVVj
            eEJCaTlwN0tBUkhIeXowODBEUDFoNTgKAo5DQ8gKTtJpwXWBcm4n3drZW93sbpfE
            Goucy010AZgqs9OnQZeS3q8bH78elDBEgBTtKGYz1v7EInqQwLvtcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T10:28:34Z"
    mac: ENC[AES256_GCM,data:XlknnDfnsl2P/mqEQNU4FIueRX3o4na1ooiNgd/E6iABePZoawPletfYQSjsd2w6t1oJdzt/JqYYNcXKSdUT9b8kOqRKYfhXCuaX2RWxH8gwei6uPH+RGHyBnhFKhPihX1dEcEB3kgieQUjQS9b1JX9l8YX2ahqZq/9f5qvAR/Y=,iv:9r++6TEf9efcQNoWrI5xVH1R5txby7vME2Omy212IdE=,tag:BBj5GPEVrCZ/W2+6/3ilmw==,type:str]
    pgp: []
    encrypted_regex: ^(apiKey|appUserPassword|otelUserPassword|harborAdminPassword|totpVaultKey|kimaiAppSecret|kimaiAdminPassword|GITHUB_CLIENT_ID|GITHUB_CLIENT_SECRET|GITHUB_PRIVATE_KEY|woosh|root_password|rspamd_password|pgdb_password|matrix_access_token|pgdb_remote_url|hmac_secret_key|adminPassword|adminEmail|jenkinsAdminEmail|securityRealm|gerrit.config|routing_key|DATABASE_URL|SMTP_PASSWORD|SECRET_KEY_BASE|admin_password|extraCommands|key|clickhouseDatabaseURL|databaseURL|client_id|client_secret|secret_key_base|otp_secret|private_key|public_key|primaryKey|deterministicKey|keyDerivationSalt|token|clientId|secretKey|installationId|installationKey|uriOverride|adminToken.value|password.value|sql_password|erlangCookie|AUTHENTICATION_PASSWORD|ROOM_API_SECRET_KEY|adminPassword|configPassword|adminUser|configUser|MAIL_PASSWORD|APP_KEY|api_key|api_secret|keys|livekit_key|livekit_secret|secret_key|admin_pass|admin_email|mariadbPassword|mariadbRootPassword|privateKey|data|stringData|PASSWD|password|pass|postgresPassword|postgresqlPassword|redminePassword|smtpPassword|registration_shared_secret|shared_secret|secret|admin_token|integrationKey|integration_key|rootPassword|adminPassword|adminUser|adminEmail|emailPassword|secretKey|appId|clientSecret|webhookSecret)$
    version: 3.9.1
