apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mediawiki-db
  namespace: mediawiki
spec:
  maxScaleRef:
    name: mediawiki-maxscale
  rootPasswordSecretKeyRef:
    name: mediawiki-cred
    key: admin-password
  database: mediawiki
  username: mediawiki
  passwordSecretKeyRef:
    name: mediawiki-cred
    key: password
  image: "docker.io/library/mariadb:12.2"
  replicas: 3
  replication:
    enabled: true
    semiSyncEnabled: false
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  podDisruptionBudget:
    maxUnavailable: 1
  affinity:
    antiAffinityEnabled: true
  storage:
    size: 2Gi
    storageClassName: longhorn
  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    innodb_buffer_pool_size=128M
    max_allowed_packet=64M
    max_connections=50
    skip_name_resolve=ON
    slow_query_log=ON
    long_query_time=1
  livenessProbe:
    periodSeconds: 10
    timeoutSeconds: 10
  readinessProbe:
    periodSeconds: 10
    timeoutSeconds: 10
  startupProbe:
    failureThreshold: 30
    periodSeconds: 10
    timeoutSeconds: 10
  resources:
    requests:
      memory: 512Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 400m
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MaxScale
metadata:
  name: mediawiki-maxscale
  namespace: mediawiki
spec:
  replicas: 2
  mariaDbRef:
    name: mediawiki-db
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 512Mi
