apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mediawiki-db
  namespace: mediawiki
spec:
  rootPasswordSecretKeyRef:
    name: mediawiki-cred
    key: admin-password
  database: mediawiki
  username: mediawiki
  passwordSecretKeyRef:
    name: mediawiki-cred
    key: password
  image: "docker.io/library/mariadb:12.2"
  replicas: 3
  galera:
    enabled: true
    recovery:
      enabled: true
    agent:
      gracefulShutdownTimeout: 90s
  affinity:
    antiAffinityEnabled: true
  storage:
    size: 2Gi
    storageClassName: longhorn
  myCnf: |
    [mysqld]
    innodb_buffer_pool_size = 128M
    max_allowed_packet = 64M
    max_connections = 50
    skip_name_resolve = ON
    slow_query_log = ON
    long_query_time = 1
  livenessProbe:
    initialDelaySeconds: 120
    periodSeconds: 20
    timeoutSeconds: 10
    failureThreshold: 10
  readinessProbe:
    initialDelaySeconds: 120
    periodSeconds: 20
    timeoutSeconds: 10
    failureThreshold: 10
  resources:
    requests:
      memory: 512Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 400m
