apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediawiki-images
  namespace: mediawiki
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
