apiVersion: v1
kind: Secret
metadata:
    name: mediawiki-cred
    namespace: mediawiki
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:4iccnOkYuNOOlF2j3RFYrrd1XxfckHquK70ocAD++SZ/3GdP1a4ToGqftU9Qz/i/87sHJE6h4CbW6GKvGqS+,iv:UAwdGnn9qCqOIwQG0OHuyjo8Btz4agbix4s4nt/jc7w=,tag:TRUzkYCUdmIwMX9j28TkFg==,type:str]
    username: ENC[AES256_GCM,data:dzbJDZo9eEIl,iv:liPkf1b9UBbuRZK5ua6i8yzI1KE2tzREgJ7Jp/DBfRc=,tag:VqMx+lwigml1ip3nB0WpMw==,type:str]
    password: ENC[AES256_GCM,data:ppNDnhRQ5qma2vBB2E7Fel7LTHlLY1fbNySj0sG0SB32fgHj6CkaNGk/FADhJI3+4FMQfg/WZnzWtR703VCx,iv:T6P5/AeLGzLPblDxoI6voD6KXmC47FoqMROB/Bkj02g=,tag:FTgFotah7awSLZfHRBCu9Q==,type:str]
    db-name: ENC[AES256_GCM,data:uZvbZxC77udL,iv:P/FQiUTsNIp4+2N61EtfVUwYchTSzw8sEbAGEzgOc4M=,tag:8IpWoLyS5JGGVplLMBPuyQ==,type:str]
    wg-secret-key: ENC[AES256_GCM,data:87EyhMcbM02Bgyrv0LF8DhyaTaM1x2wkYPipz5NsfQQrxr69h9FYe7dq64CBagiSX3Otf9dPSy1Iy0ffrXx/Zw==,iv:pPgrTzsANqihkxRL5l4fQ2SSdOHRNcrarGQMY4+Jbe0=,tag:AcR9uEPTXIxOP9fQzbq9vg==,type:str]
    wg-upgrade-key: ENC[AES256_GCM,data:dAxQB5CEwckztCbJg/TsK4nroL39hg47ITBvkzic7hsApty6ql2+SbDSODDOCr2k5THCOy1p477ligrKpkTF7A==,iv:DUV/yOp02yy/J4pQAwJewIH3gYitp5xAsrSF28ejI/c=,tag:l/sKkCIqZ6Fhc50sV+/kTQ==,type:str]
    smtp-password: ENC[AES256_GCM,data:x83ePJ3rCeYxaBajd+8l0Y8RRIMpnwchqlyvMFu1OEoHQqdICd1ueXRLle9REw7q2MYRJQBYEUW/qb6S7yGVkQ==,iv:8+C1nQHm2F1/Jkl87Vi385uo+rRWAkGD4npcjFP6YT4=,tag:3J72OEk16fGRB//rA4Eyug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1esjyg2qfy49awv0ptkzvpk425adczjr38m37w2mmcahzc4p8n54sll2nzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WFU1a3V6c0JObE5QQnRL
            eWxMaHZJSGZOaGJJQUpCb2J0Z0M0ZmdrZ3hrCjJyMC9XMUF1R0VWZ2NRdFplcUZX
            NTVPM1hYaW9GN3FSUGtPUmp5bXA1aWMKLS0tIDgxRVhXbGRrMWFqTzZ1VUxhVmpo
            RUhtR2Fodm1qZkxySW1wTWQ0TjhjemMKqcwFTSUeP60BDJh3Q9afAdsGmzYf2A3Y
            UP8dXy0zjirgwaWJgrBRFgiI5fKY2q3RBGBT0wBkJ60Uydg+3H9Trg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T17:30:09Z"
    mac: ENC[AES256_GCM,data:MObb5ckUVaYhhnXchihZSFN4DdfLCbNxgrCsBGnrE+HiSoKektP9D7Fk0q74o03nhpZGBeLb3m1a3zXuoPRepfx/4ys+/ya2dtuFsCg5Flh758gYDeeyiFigqcFY3v5b3ZNg1iO/ZUv4+c2EJTSufchUFbjwb2xrNQM7ZXXC3MQ=,iv:0LR5/rU/3/LugwyOSN6Zt6DriKGdFiXInGfYrUSvM/M=,tag:/AumxnfLB2m3aaMLwwoTmQ==,type:str]
    pgp: []
    encrypted_regex: ^(apiKey|appUserPassword|otelUserPassword|harborAdminPassword|totpVaultKey|kimaiAppSecret|kimaiAdminPassword|GITHUB_CLIENT_ID|GITHUB_CLIENT_SECRET|GITHUB_PRIVATE_KEY|woosh|root_password|rspamd_password|pgdb_password|matrix_access_token|pgdb_remote_url|hmac_secret_key|adminPassword|adminEmail|jenkinsAdminEmail|securityRealm|gerrit.config|routing_key|DATABASE_URL|SMTP_PASSWORD|SECRET_KEY_BASE|admin_password|extraCommands|key|clickhouseDatabaseURL|databaseURL|client_id|client_secret|secret_key_base|otp_secret|private_key|public_key|primaryKey|deterministicKey|keyDerivationSalt|token|clientId|secretKey|installationId|installationKey|uriOverride|adminToken.value|password.value|sql_password|erlangCookie|AUTHENTICATION_PASSWORD|ROOM_API_SECRET_KEY|adminPassword|configPassword|adminUser|configUser|MAIL_PASSWORD|APP_KEY|api_key|api_secret|keys|livekit_key|livekit_secret|secret_key|admin_pass|admin_email|mariadbPassword|mariadbRootPassword|privateKey|data|stringData|PASSWD|password|pass|postgresPassword|smtp_auth_password|addresses|smtp_auth_username|authorization_credentials|postgresqlPassword|redminePassword|smtpPassword|registration_shared_secret|shared_secret|secret|admin_token|integrationKey|integration_key|rootPassword|adminPassword|adminUser|adminEmail|emailPassword|secretKey|appId|clientSecret|webhookSecret|content)$
    version: 3.9.1
