apiVersion: v1
kind: Secret
metadata:
    name: mediawiki-cred
    namespace: mediawiki
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:jsSsW9NdIiI+kM4ADVfQ7efvSroVIjr2TnzzPA5wp7b7oZxF1wIYVC1KaNSXSKgD0MbGRFXBUoFoGoAGwakO,iv:fizRdIFYigznvaQx2PKrrlkur9xeBVM9c4hHcYaXm40=,tag:f/xaw0oCbwbT24JLbGn2VA==,type:str]
    username: ENC[AES256_GCM,data:aa2PhIgWskbN,iv:8G7gXW50kVJLSSZ6xU4UVYfDlFuTgDBQ/igGhtUII98=,tag:cPficJMzybn8D00UIguuRQ==,type:str]
    password: ENC[AES256_GCM,data:wEC6WOgM7c8guLNaT8YoWcnhg9Zftsjkb+nQ7Sj4kiCfke00XLtWS0HyUVWsslfqLzQGMI/M0pwS7wrgiGJQ,iv:X+NSDlh6+m8oUbNZUuFB4liDLzIvJWmFE5YIVpqOHO4=,tag:9ZJ45S8v3iwr65YWjEMfJQ==,type:str]
    db-name: ENC[AES256_GCM,data:RQmXW7fjWHmv,iv:YVs4cBxiqCnvEbTjeuRln4+f83FW0gAIVyKKAoWZDy8=,tag:ZAL90n0XTOpZb43FpSO4FA==,type:str]
    wg-secret-key: ENC[AES256_GCM,data:6G1TYtL+lGkS7upUmXt0kQ8HSJatvURdSXeBv0pGgs30nyof7InMhgRzTVd7Z04pxsK+ToEPhX4/lnC91XwTOQ==,iv:Woo1gQqyYnpsQ7qCS/nSj2z92mLHsxpi5kUMvsTsuzk=,tag:AVfdKROYOgAM0ASqLERaow==,type:str]
    wg-upgrade-key: ENC[AES256_GCM,data:mqtfeKlp2F3SCWEh3nwVS+ZSQcsXOIFy0allk+zEUdLMUtMCzXSj+JZbWon+3YQtMJcJY3JfX4aX80c8Na7f4A==,iv:OdWpLVBakHjHtM/zYYN0uCEgiMLH72oY1ycp/iihY1k=,tag:OkTrj1jUHhtl12Foerthcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1esjyg2qfy49awv0ptkzvpk425adczjr38m37w2mmcahzc4p8n54sll2nzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRnltRUphOEh2WGZXVzZF
            L3hkcjVEdTkxK21rR1NQTDAyQ2UrMFVORWdvCkFUNjBYNDkyZ1ZCc2JZbDNSaEht
            ZXJGOENmdmRSa293K2lYTmgxemNoVm8KLS0tIDNrUVh1dFVmSFdxYlBudXh3VHRB
            SWJwY2djTFVvR0YxdWlaL2UrbzVxOUEKIA610Ni152yvC6Lhcmf4XwtzBPv2z2Mk
            ve7xkqt5l4jRNf3Bgwl7vdF/SLGOa5tkKlPHbPcxvn22WN4fDVa7Wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T14:57:29Z"
    mac: ENC[AES256_GCM,data:v7Okh91u92n866eEasiAUGQV/EQ0a+/Eh9f2aiMkpYWILTx9U6c4W7OoqUqoKQv6OlaeJm5mqm+Pdioa1Ip60PZtChcDWgbFHX/HHQ8DPU1iG1/g48GUy6zFr5PXaT+sJyjtiNfhZple2JzuoXrFe0weTc1mbEpfK4n8+VexQZc=,iv:cr0iS4FIxyTaJPzg8OQbcVcDVPjhafltfyklV4iAZJI=,tag:gjdeUtFypvjJY8ziwND6uQ==,type:str]
    pgp: []
    encrypted_regex: ^(apiKey|appUserPassword|otelUserPassword|harborAdminPassword|totpVaultKey|kimaiAppSecret|kimaiAdminPassword|GITHUB_CLIENT_ID|GITHUB_CLIENT_SECRET|GITHUB_PRIVATE_KEY|woosh|root_password|rspamd_password|pgdb_password|matrix_access_token|pgdb_remote_url|hmac_secret_key|adminPassword|adminEmail|jenkinsAdminEmail|securityRealm|gerrit.config|routing_key|DATABASE_URL|SMTP_PASSWORD|SECRET_KEY_BASE|admin_password|extraCommands|key|clickhouseDatabaseURL|databaseURL|client_id|client_secret|secret_key_base|otp_secret|private_key|public_key|primaryKey|deterministicKey|keyDerivationSalt|token|clientId|secretKey|installationId|installationKey|uriOverride|adminToken.value|password.value|sql_password|erlangCookie|AUTHENTICATION_PASSWORD|ROOM_API_SECRET_KEY|adminPassword|configPassword|adminUser|configUser|MAIL_PASSWORD|APP_KEY|api_key|api_secret|keys|livekit_key|livekit_secret|secret_key|admin_pass|admin_email|mariadbPassword|mariadbRootPassword|privateKey|data|stringData|PASSWD|password|pass|postgresPassword|smtp_auth_password|addresses|smtp_auth_username|authorization_credentials|postgresqlPassword|redminePassword|smtpPassword|registration_shared_secret|shared_secret|secret|admin_token|integrationKey|integration_key|rootPassword|adminPassword|adminUser|adminEmail|emailPassword|secretKey|appId|clientSecret|webhookSecret|content)$
    version: 3.9.1
