apiVersion: v1
kind: ConfigMap
metadata:
  name: zot-cosign-pubkey
  namespace: zot
data:
  cosign.pub: |
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEw9fvLAgkWk7gjyqL7zFwsaVjio27
    ZN0AmKDg6Xn/hIfuvQRCZSlsobHpbxddDuoSEfQsDU0DEeFD7TxV2BsmpA==
    -----END PUBLIC KEY-----
