apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: jenkins-instance
  namespace: jenkins

resources:
  - jenkins-casc-configmap.yaml
  - registry-secret.yaml
  - cosign-secret.yaml
  - jenkins-instance.yaml
