apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: base-images
  namespace: flux-system
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      message: "chore(base-images): auto-update base image digests"
    push:
      branch: main
  update:
    path: ./apps/talos_cluster/
    strategy: Setters
