apiVersion: v1
kind: Namespace
metadata:
    name: longhorn-system
    labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1esjyg2qfy49awv0ptkzvpk425adczjr38m37w2mmcahzc4p8n54sll2nzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNiswVXNZNkR2bTN1S1JL
            TDNBWkJYTGp1SWRpZzZmZmM0VkFmenRJRW5JCkN1dUhoS05LQlVTU0RDRWM5TEJ0
            dk43WWVqZVZ0V0xUeFhWK0ZBMkNia0EKLS0tIEhDQjQ2bjRGa1FaMGpSeStOSk0v
            dWRvY3hkR0REQms2NjhuWnhvbDV4UjgKNnPh5R/0PFIBVjlyMMf+PRkPhITRDODt
            tl84LXYOcTVQHMKsymOsrAzhBvYk7bUC9hRGUJyb3ZoS29tNIKXnDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T21:28:03Z"
    mac: ENC[AES256_GCM,data:p2Oin9eakHc3Kv+ok6mFv8+sPf/f77UtUCQlm2J5PsI9woxrGr51I+M8gXy2/LuvUUHykaE9uDjpYifArtmd7hzMSoD54hWbEGZWVhqWo5rNVc1fnBomb62BxULCJAzB7wwkDPJllJOSuT7OZGgmncGxcML3VhPZppXyuxi6WXA=,iv:BINk8FpRShMLH8RvPbsNo1ZHLJPGIcd9ogVgM1LbyJQ=,tag:jZ1UG5gG0A8OmYbLiHPzkw==,type:str]
    pgp: []
    encrypted_regex: ^(apiKey|appUserPassword|otelUserPassword|harborAdminPassword|totpVaultKey|kimaiAppSecret|kimaiAdminPassword|GITHUB_CLIENT_ID|GITHUB_CLIENT_SECRET|GITHUB_PRIVATE_KEY|woosh|root_password|rspamd_password|pgdb_password|matrix_access_token|pgdb_remote_url|hmac_secret_key|adminPassword|adminEmail|jenkinsAdminEmail|securityRealm|gerrit.config|routing_key|DATABASE_URL|SMTP_PASSWORD|SECRET_KEY_BASE|admin_password|extraCommands|key|clickhouseDatabaseURL|databaseURL|client_id|client_secret|secret_key_base|otp_secret|private_key|public_key|primaryKey|deterministicKey|keyDerivationSalt|token|clientId|secretKey|installationId|installationKey|uriOverride|adminToken.value|password.value|sql_password|erlangCookie|AUTHENTICATION_PASSWORD|ROOM_API_SECRET_KEY|adminPassword|configPassword|adminUser|configUser|MAIL_PASSWORD|APP_KEY|api_key|api_secret|keys|livekit_key|livekit_secret|secret_key|admin_pass|admin_email|mariadbPassword|mariadbRootPassword|privateKey|data|stringData|PASSWD|password|pass|postgresPassword|smtp_auth_password|addresses|smtp_auth_username|authorization_credentials|postgresqlPassword|redminePassword|smtpPassword|registration_shared_secret|shared_secret|secret|admin_token|integrationKey|integration_key|rootPassword|adminPassword|adminUser|adminEmail|emailPassword|secretKey|appId|clientSecret|webhookSecret)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: backup-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:FlkMN67HdstKGLVFOVoIye4ONfo=,iv:c6/2HDqsqHYX4HuaGvhOcuXNo8ninBlwjdQ+rFXp+IA=,tag:rIr7rNKdXxHWAX6MAiAIXA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:+lzeJU/6ybhCLWnh2DySL7yf0MLBXJiPZjBD84vLdX8C9yYaqqomwQ==,iv:kSX0jdGZ2FeDP4LGZn+/PcOOHUGoFgaJ98Hsi330Bh4=,tag:6Yx2s8IMdUukhf8cEEflog==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:gw+inzGWsyJ5kWcJ+D53R82RpM5tuUiK8UwVcplNUZLhk9Y=,iv:nK3G2/GfDCwPOPAX6fEPEI5myUyoj6cLW1T7KW3SsOk=,tag:AZ/CjkdRpRaIjsJ9db5DiQ==,type:str]
    VIRTUAL_HOSTED_STYLE: ENC[AES256_GCM,data:zMI+Sw==,iv:my+XFrJA0jYcoCZzJQ5RzLC6Tsa6bmts9Gp8gTHZRgo=,tag:Hu0aMjiz+XiZcImx3ebnQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1esjyg2qfy49awv0ptkzvpk425adczjr38m37w2mmcahzc4p8n54sll2nzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNiswVXNZNkR2bTN1S1JL
            TDNBWkJYTGp1SWRpZzZmZmM0VkFmenRJRW5JCkN1dUhoS05LQlVTU0RDRWM5TEJ0
            dk43WWVqZVZ0V0xUeFhWK0ZBMkNia0EKLS0tIEhDQjQ2bjRGa1FaMGpSeStOSk0v
            dWRvY3hkR0REQms2NjhuWnhvbDV4UjgKNnPh5R/0PFIBVjlyMMf+PRkPhITRDODt
            tl84LXYOcTVQHMKsymOsrAzhBvYk7bUC9hRGUJyb3ZoS29tNIKXnDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T21:28:03Z"
    mac: ENC[AES256_GCM,data:p2Oin9eakHc3Kv+ok6mFv8+sPf/f77UtUCQlm2J5PsI9woxrGr51I+M8gXy2/LuvUUHykaE9uDjpYifArtmd7hzMSoD54hWbEGZWVhqWo5rNVc1fnBomb62BxULCJAzB7wwkDPJllJOSuT7OZGgmncGxcML3VhPZppXyuxi6WXA=,iv:BINk8FpRShMLH8RvPbsNo1ZHLJPGIcd9ogVgM1LbyJQ=,tag:jZ1UG5gG0A8OmYbLiHPzkw==,type:str]
    pgp: []
    encrypted_regex: ^(apiKey|appUserPassword|otelUserPassword|harborAdminPassword|totpVaultKey|kimaiAppSecret|kimaiAdminPassword|GITHUB_CLIENT_ID|GITHUB_CLIENT_SECRET|GITHUB_PRIVATE_KEY|woosh|root_password|rspamd_password|pgdb_password|matrix_access_token|pgdb_remote_url|hmac_secret_key|adminPassword|adminEmail|jenkinsAdminEmail|securityRealm|gerrit.config|routing_key|DATABASE_URL|SMTP_PASSWORD|SECRET_KEY_BASE|admin_password|extraCommands|key|clickhouseDatabaseURL|databaseURL|client_id|client_secret|secret_key_base|otp_secret|private_key|public_key|primaryKey|deterministicKey|keyDerivationSalt|token|clientId|secretKey|installationId|installationKey|uriOverride|adminToken.value|password.value|sql_password|erlangCookie|AUTHENTICATION_PASSWORD|ROOM_API_SECRET_KEY|adminPassword|configPassword|adminUser|configUser|MAIL_PASSWORD|APP_KEY|api_key|api_secret|keys|livekit_key|livekit_secret|secret_key|admin_pass|admin_email|mariadbPassword|mariadbRootPassword|privateKey|data|stringData|PASSWD|password|pass|postgresPassword|smtp_auth_password|addresses|smtp_auth_username|authorization_credentials|postgresqlPassword|redminePassword|smtpPassword|registration_shared_secret|shared_secret|secret|admin_token|integrationKey|integration_key|rootPassword|adminPassword|adminUser|adminEmail|emailPassword|secretKey|appId|clientSecret|webhookSecret)$
    version: 3.9.1
