apiVersion: v1
kind: Secret
metadata:
    name: wanderer-secrets
    namespace: wanderer
type: Opaque
stringData:
    #ENC[AES256_GCM,data:HXctxNtSq0MEYb/iiSF83nn9/T7sU1V05DjNebWxufXcvepr,iv:nFqzfybzk3njYXocNzsElVr+P8pb5DjINBFZU3RKHM0=,tag:Nvzmtx2Dpy0Gggb9qb3/5g==,type:comment]
    POCKETBASE_ENCRYPTION_KEY: ENC[AES256_GCM,data:buOq8QUtO5Gte+zLfI6aQA9yg4w/LUTffVQOWDwf3u4=,iv:HJSBqzUEsWljKD9QdsInbUWhM70UdsEu/ObHkVBFEAY=,tag:cF+jSh4f8hsuyFd8q89Krg==,type:str]
    #ENC[AES256_GCM,data:TP7rMwI3HFJJ5h1auTI/zzq6iys3bMBhoF6ACvM7kT2G2DzVeqhI,iv:0XnvDcbENHlQJHxuZIU9WH9a7G/eA/N3ayOG6MJE/cg=,tag:lccgKvEPu40eQ96neMeWMg==,type:comment]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:ClCkNv7WjrXKcMWRkHqBHzzddNK/ELtl3Fg4vXWmGdiubOdSatPXIqtgDlHRgSVNAHOp5vMuogqeBryahLV2,iv:dLVNck9rQ3QiOl2+V6En2XRMWfK5/7MNuddyu9vl9rI=,tag:ykUbBrHGmEhhU/1WSeM2Cw==,type:str]
    POCKETBASE_SMTP_HOST: ENC[AES256_GCM,data:mTqbGEpAGHIfDQ1AggmzyO4VRX7/BwNmmu1g,iv:Y2PNUMWCVRkuzRqLK0oELIi7XqAC6NDFG91YRk/jKcI=,tag:+4ZF/YryW+9vkulH17i0+A==,type:str]
    POCKETBASE_SMTP_PORT: ENC[AES256_GCM,data:xW4p,iv:QGwT+6SnI5BKo+HVx+Ie9FOm2ew7XiRvnmUDu0XisSw=,tag:/gk9jsTaPRDpwb1wGPvT8Q==,type:str]
    POCKETBASE_SMTP_USERNAME: ENC[AES256_GCM,data:hLcjzXJSLwza319Si3FnX32WCF4WrxveiPoSiNcazg==,iv:zeNjgJzTGA4YkzeC/Uy7D6VNs3oj5depgqIENOoguJY=,tag:ycMrmVZA6o7MxEiBdiv1Gw==,type:str]
    POCKETBASE_SMTP_PASSWORD: ENC[AES256_GCM,data:JQccYz9Lj127V1m2RLyyX02qRGtw1z6EoOw/jHS5/OxBlKocRUmWGXnaN0WoXTMrssADL5gS9gbv+wnqFJt9,iv:WNMWu4A4ZF7pzmkXN/7E2ImG3EmIuKfHk3JlGlYsll8=,tag:UMMLFUhvbjveuc5YijFImw==,type:str]
    POCKETBASE_SMTP_SENDER_ADDRESS: ENC[AES256_GCM,data:aqNfw8yuo05lAVS6Pwqevf/Ix2383RrH75E5PUPa9Q==,iv:9n+CnP4GQKMuGvqwseLt6CZbrZdjco0r82826N05gW8=,tag:zvfzaPBkJkwCBAa/jpiLhQ==,type:str]
    POCKETBASE_SMTP_SENDER_NAME: ENC[AES256_GCM,data:XIImn7d9lks=,iv:xh/DfD7vbEITgjEalVUziBIhi8oeSt4vWOu7dQlS3Os=,tag:Qrtrir39iP0WCOU2jjYpYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1esjyg2qfy49awv0ptkzvpk425adczjr38m37w2mmcahzc4p8n54sll2nzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbGE5MzJVbWdHS1pJUC9G
            RkV4NUUxZmtvaXp1MUYxM3VTdDdaRWVxU0NvCjdmUWdyMitsVWgvQ0lMR3Z5cm9h
            RVNhRU9sWWxrRXNNZ1BwczQ4NnhYK00KLS0tIFBaSms4b1Z1d0l4ektzREgzanFa
            dHdpZEg2VTVKRUVwcjFqZ3FKVTlWNVUKavrTBaliicob5wHzhol90je/OUM/GODG
            X4CCX052er8KOMQUYtIPbKfBATV9eSV67HahpTSsfmwGrGZAkLmH/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T18:18:40Z"
    mac: ENC[AES256_GCM,data:NzT8CVBt37Z0oqk9Mk26e3IKtOB+8KFt6yTL5fex2VAiJZDkA1cwhfmlk2EPH7e+BPzslHJjwLvK70BhJIovPiGhE18xmAiMXNFLa2Bw4Ztjq/1f1HorUafoWQLq7EshoGfF2zpBuZW9OstmrWcU8CKYHTZMV38C9drDoDbD0uA=,iv:brfp4wcJZaFMUgtuQpGt5Hh5rXrQb65PGsoZL4Ie25A=,tag:Z0DtMdu1XJGMdLK/7uu+Hg==,type:str]
    pgp: []
    encrypted_regex: ^(apiKey|appUserPassword|otelUserPassword|harborAdminPassword|totpVaultKey|kimaiAppSecret|kimaiAdminPassword|GITHUB_CLIENT_ID|GITHUB_CLIENT_SECRET|GITHUB_PRIVATE_KEY|woosh|root_password|rspamd_password|pgdb_password|matrix_access_token|pgdb_remote_url|hmac_secret_key|adminPassword|adminEmail|jenkinsAdminEmail|securityRealm|gerrit.config|routing_key|DATABASE_URL|SMTP_PASSWORD|SECRET_KEY_BASE|admin_password|extraCommands|key|clickhouseDatabaseURL|databaseURL|client_id|client_secret|secret_key_base|otp_secret|private_key|public_key|primaryKey|deterministicKey|keyDerivationSalt|token|clientId|secretKey|installationId|installationKey|uriOverride|adminToken.value|password.value|sql_password|erlangCookie|AUTHENTICATION_PASSWORD|ROOM_API_SECRET_KEY|adminPassword|configPassword|adminUser|configUser|MAIL_PASSWORD|APP_KEY|api_key|api_secret|keys|livekit_key|livekit_secret|secret_key|admin_pass|admin_email|mariadbPassword|mariadbRootPassword|privateKey|data|stringData|PASSWD|password|pass|postgresPassword|smtp_auth_password|addresses|smtp_auth_username|authorization_credentials|postgresqlPassword|redminePassword|smtpPassword|registration_shared_secret|shared_secret|secret|admin_token|integrationKey|integration_key|rootPassword|adminPassword|adminUser|adminEmail|emailPassword|secretKey|appId|clientSecret|webhookSecret|content)$
    version: 3.9.1
