apiVersion: v1
kind: Secret
metadata:
    name: wanderer-secrets
    namespace: wanderer
type: Opaque
stringData:
    #ENC[AES256_GCM,data:vG/HRSM/LPQZ7xjLHx8JVy/VT+EHYAnu/XvZ8Cl8Hv0mdGTG,iv:Up8aVwvw5MLQDOnXnKLF3/FKePls2QQDRW9/+9NKIYg=,tag:LzA7OBij7SErnl0aK/SI1A==,type:comment]
    POCKETBASE_ENCRYPTION_KEY: ENC[AES256_GCM,data:NMGVPX+uTqf5bsY1ZcoPe710oik4id6MzLiHGrnMPPw=,iv:N6Gn2G2XlrB3eVpQwEwtU1QCXnMh+gjaq9C/CPitgWk=,tag:YUO4HcmbycZGVeqM+9i9xg==,type:str]
    #ENC[AES256_GCM,data:bTRYkId+LN90Dh/W+e/5I0JEDnehxnfpDOJrrRmppd6Es80OKV9I,iv:obOg48tY6XDpDd/TtSS6KNe4ea7CmN/LuAGEnxBWB9w=,tag:JDJFCgUfXq2+aSe5B7n7lQ==,type:comment]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:5JPrsuEYMD0jI4xI1j7wxw0epSSzCcClFf94I5fnYRBUxyrV1D5cWc5xq6E5DsxztxRXdCuGd7KB7tjHCHwO,iv:E+UFLAUFRJFim3+eC6RcGM6QhSIAI+7EegLzeXCvcZA=,tag:ihK04pltp9eYswYmDTcFAA==,type:str]
    POCKETBASE_SMTP_HOST: ENC[AES256_GCM,data:qmplnWDMg08LX7EThKw2f9CdiM3MojE+oT1/,iv:VCWlnFdvXOXZq+IfDq6x+uij8x9UFqN9IEcHOnXgP/k=,tag:dq5Tb7PZs9OY50rGUIRawg==,type:str]
    POCKETBASE_SMTP_PORT: ENC[AES256_GCM,data:GVUp,iv:Q1bfpsyDXqXxahW098IGglOLkq37TuD0ETlESoiEvrI=,tag:5Y7lcEJqo899il08QpMX/w==,type:str]
    POCKETBASE_SMTP_USERNAME: ENC[AES256_GCM,data:YWBBBsiBZ3FI6H3pNaa02uOPfUVzc2pS+HOTo7ZDCQ==,iv:032lCs7oDd5UGbCHwtOTXwcjGAoDC1eF7UYsSgr6+PI=,tag:08NDXNa3Kn0ak8x2CjN2Kw==,type:str]
    POCKETBASE_SMTP_PASSWORD: ENC[AES256_GCM,data:OGxbLar9TQUiFH9iKCnF3KCciXumlRUqCioNTj5bWLproOyBUhGOmC3o5E/WvrZjud7bhu+2O2hFl5i4i7xM,iv:vxjpZuZRJT+Z88P2tonPyZAZl8jXa60QfHCvdbYQfJU=,tag:YRYt6+jmh/YKucH4nJTAdw==,type:str]
    POCKETBASE_SMTP_SENDER_ADDRESS: ENC[AES256_GCM,data:3mb/4q89G9jo/Ea8HH1PhmcpY3lW,iv:sQaG078KUKcxa9qcQ/gx4gGelIyhjskhAk22lzV6wPg=,tag:xiTLI7b4qyPl6pT9mDaldw==,type:str]
    POCKETBASE_SMTP_SENDER_NAME: ENC[AES256_GCM,data:4IjSH2YZfrc=,iv:v3rQGo6CNsDwy/kgdvQXfSvx+9IYFwT5iNi+2D/6r68=,tag:Nr/B1AZW7stNMcMxyqYNtg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1esjyg2qfy49awv0ptkzvpk425adczjr38m37w2mmcahzc4p8n54sll2nzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdElkeUVtTHRjQldBeFpE
            MjRicVhsVUxDbThmY2RTQkVUNzU5Y0IwOGc4CnNHU3RnWmZ4RnZQSUlsNjB5K29I
            Z1Qya3ZQemZOQnBLaXFxZjVKK0UzSUEKLS0tIFNxZFhnVWhjSWMwcnN6RVRjc2V0
            WFhBK09EU2t5ZmxLV21JUUJpWktqMmsKgDniMoiwHu0zyc1v636qNuJuL34+ifyD
            EyR1VPWEfOPYrMRUuM/E8DKK6Z+YsV1iGUQH6fpW0GeE7yIqNmPldQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T18:04:51Z"
    mac: ENC[AES256_GCM,data:mnhHk9oWRML/K7tomayhgpb+cCyKsmvY6/ZlPba5JmvbCGGMfSJUzHvBMd3PmtN9kdkQDJWiET/T9jTd8v53WUt4fQdZ9Tunkh6J1TVRpbulExC/A6tIii+ghwrZl744QHdeZhUO9Tolav641B/stiU+ntAvt8jKS1qp1l1+ty8=,iv:ZAuGd2NbqfdUVsO1uxMFzRIy19SzhuJbVL+mTvolfjY=,tag:S6DwaNfEC6b7nBD93Gc3eQ==,type:str]
    pgp: []
    encrypted_regex: ^(apiKey|appUserPassword|otelUserPassword|harborAdminPassword|totpVaultKey|kimaiAppSecret|kimaiAdminPassword|GITHUB_CLIENT_ID|GITHUB_CLIENT_SECRET|GITHUB_PRIVATE_KEY|woosh|root_password|rspamd_password|pgdb_password|matrix_access_token|pgdb_remote_url|hmac_secret_key|adminPassword|adminEmail|jenkinsAdminEmail|securityRealm|gerrit.config|routing_key|DATABASE_URL|SMTP_PASSWORD|SECRET_KEY_BASE|admin_password|extraCommands|key|clickhouseDatabaseURL|databaseURL|client_id|client_secret|secret_key_base|otp_secret|private_key|public_key|primaryKey|deterministicKey|keyDerivationSalt|token|clientId|secretKey|installationId|installationKey|uriOverride|adminToken.value|password.value|sql_password|erlangCookie|AUTHENTICATION_PASSWORD|ROOM_API_SECRET_KEY|adminPassword|configPassword|adminUser|configUser|MAIL_PASSWORD|APP_KEY|api_key|api_secret|keys|livekit_key|livekit_secret|secret_key|admin_pass|admin_email|mariadbPassword|mariadbRootPassword|privateKey|data|stringData|PASSWD|password|pass|postgresPassword|smtp_auth_password|addresses|smtp_auth_username|authorization_credentials|postgresqlPassword|redminePassword|smtpPassword|registration_shared_secret|shared_secret|secret|admin_token|integrationKey|integration_key|rootPassword|adminPassword|adminUser|adminEmail|emailPassword|secretKey|appId|clientSecret|webhookSecret|content)$
    version: 3.9.1
