apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-s3-config
  namespace: blog
data:
  s3-storage.xml: |
    <clickhouse>
      <listen_host>0.0.0.0</listen_host>
      <listen_host>::</listen_host>
      <listen_try>1</listen_try>
      <storage_configuration>
        <disks>
          <s3_disk>
            <type>s3</type>
            <endpoint>https://hel1.your-objectstorage.com/midnightthoughts-clickhouse/</endpoint>
            <access_key_id from_env="CH_S3_ACCESS_KEY"/>
            <secret_access_key from_env="CH_S3_SECRET_KEY"/>
            <skip_access_check>true</skip_access_check>
          </s3_disk>
        </disks>
        <policies>
          <s3_only>
            <volumes>
              <default>
                <disk>default</disk>
              </default>
              <remote>
                <disk>s3_disk</disk>
              </remote>
            </volumes>
            <move_factor>0.99</move_factor>
          </s3_only>
        </policies>
      </storage_configuration>
    </clickhouse>
