apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plausible
  namespace: blog
spec:
  chart:
    spec:
      chart: plausible-analytics
      sourceRef:
        kind: HelmRepository
        name: plausible
  interval: 60m
  timeout: 10m
  install:
    timeout: 10m
    remediation:
      retries: 3
  values:
    baseURL: https://plausible.midnightthoughts.space
    disableRegistration: true
    totpVaultKey: ENC[AES256_GCM,data:ldeCce7QoNy/+0RxWAORXPE0YKVoNvFOZqm11HwYCmiEyDVRM5KlyC9POUs=,iv:VpaO569FIicLXtML7wfwijmX9JZkYxE2i/dzHsGzPI0=,tag:8cPs9h+UJLZCSdB2dWfuQQ==,type:str]
    clickhouseDatabaseURL: ENC[AES256_GCM,data:AwbsUpvmXx2qX7ayH3ZPV8c+FNhykmiVp/4TA0ehp3w+n4mU+gQF4l1YSeZgkW5lgds0GR5ypjD7VQ5QVHGC2syf5RKgEyjt6CIPTyYaoPUXBVEwSVHuCU9EjTWEoZSE1vM4P2e2eXOBlWV74s6IiEqvTMDdBve/Sceqry7Aog1OnZ5qoKDHW1y388D7kv3aBfAX02LwBQ==,iv:AgKEzrl0yLF0tf66V2xrKRpOHUGrpJSvdRQmCdsVbmA=,tag:25eCAxrHRJrEAvb438a/Jg==,type:str]
    databaseURL: ENC[AES256_GCM,data:RtLJFoWpYhLJ9idi/4UHcTFbyMdnd/naRQGaSx42xouMSWZrP4b/Q+d8EjD6s3B/Sc0nr+dz7stzvmCXGaYKLhOh+kNEHPGWUxqRfy7Xw9HjvRdSpnGIypwBSqOlvCEyzQ8gaZSk77P7nf4DQ/uvONn8fVMCTo8Db3XBpRJK9EyG4kU+xV3NukNermSUeu+EQQdgyEMRycE=,iv:t8sB8N1Sv4iNmMaG9x5IpWw+7a5V3UBofa/Wt1qECow=,tag:9G4HNBXx76kHGOmGMmqc+A==,type:str]
    mailer:
      enabled: true
      adapter: Bamboo.Mua
      email: support@midnightthoughts.space
      smtp:
        host: mail.midnightthoughts.space
        port: 465
        auth: true
        username: support@midnightthoughts.space
        password: ENC[AES256_GCM,data:tOcLnFEtAFYnzEX021p6fiIngYdJ+LV1D0+25vg7gpMDn6L3VRHSAlfZJ6t1Cm4JYtVXVzHSjre26Mrzg5raLA==,iv:ECNpBgrbUZiyfghxyQAI+YxNZw8GChts2IFBu57rUz0=,tag:KnlEMJYn0jq1WHDfWbnRHA==,type:str]
        ssl: true
    postgresql:
      enabled: false
    clickhouse:
      resourcesPreset: xlarge
      auth:
        password: ENC[AES256_GCM,data:Req2rtxHw3X+SO5OY7DCn+KmQLaHbWi7H9qXi0SZa87FrCSsL+ifsMNNNDQGvwnTHYT2pxtmw07KPzog84GIJQ==,iv:SXz6fB2ryliT4brJ/aqu105vbc51Bn+FoO8pb620e9s=,tag:8Myks0ErvFV/u2ANXd6N/Q==,type:str]
      persistence:
        storageClass: longhorn
        enabled: true
        size: 256Mi
      extraEnvVarsSecret: clickhouse-s3-credentials
      extraVolumes:
        - name: s3-config
          configMap:
            name: clickhouse-s3-config
      extraVolumeMounts:
        - name: s3-config
          mountPath: /etc/clickhouse-server/conf.d/s3-storage.xml
          subPath: s3-storage.xml
    ingress:
      enabled: false
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-dns
      hosts:
        - plausible.midnightthoughts.space
      path: /
      tls:
        - secretName: plausible.midnightthoughts.space-tls
          hosts:
            - plausible.midnightthoughts.space
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1esjyg2qfy49awv0ptkzvpk425adczjr38m37w2mmcahzc4p8n54sll2nzh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQR251UUhSU2ZqVm1pUVN4
        RnREUmJNcEpLNXBQcnF3WHBUSWVLNmpHL0cwCjdlaXYwS3dRN2FaL3R0eVBmekVk
        YURoc2xhS0xjTDYzRmQ3TzY4Rkhja0kKLS0tIFlvUkhjemNiSGVpTmk1TDJLbEtF
        NERGS1FzcTRzVTRJd3JJc25HYlFVZmMKBAEkQScgubc7gfzYN3n24CcCuG0CmRkx
        ce5adx6anV5hvMV91fimc3qlnRjh48kGXhp/dSqF+gNKtGDBs5wKRw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-03T20:55:58Z"
  mac: ENC[AES256_GCM,data:rEuFtr98S2Og0MCYTR2G8yv0MILypcf8T9eXX9N4I+jBZ7s4f1MHCLxwOba8ME79XzX/yzS7zmvhVwyUYRu4pjcMhi2et229XjmggKWuMeYO3buaUPQtFUE3l77hk6N22KhbEbu9o7vtulnIUmeNfOldw1b6x3fhV4i6t4KuBIM=,iv:E52xnbqoqrpcfaFbFGa+Fh+eMl1FBlmgCmw0UKruEbw=,tag:T4KUkot3E2lp/4xwn3Humw==,type:str]
  pgp: []
  encrypted_regex: ^(apiKey|appUserPassword|otelUserPassword|harborAdminPassword|totpVaultKey|kimaiAppSecret|kimaiAdminPassword|GITHUB_CLIENT_ID|GITHUB_CLIENT_SECRET|GITHUB_PRIVATE_KEY|woosh|root_password|rspamd_password|pgdb_password|matrix_access_token|pgdb_remote_url|hmac_secret_key|adminPassword|adminEmail|jenkinsAdminEmail|securityRealm|gerrit.config|routing_key|DATABASE_URL|SMTP_PASSWORD|SECRET_KEY_BASE|admin_password|extraCommands|key|clickhouseDatabaseURL|databaseURL|client_id|client_secret|secret_key_base|otp_secret|private_key|public_key|primaryKey|deterministicKey|keyDerivationSalt|token|clientId|secretKey|installationId|installationKey|uriOverride|adminToken.value|password.value|sql_password|erlangCookie|AUTHENTICATION_PASSWORD|ROOM_API_SECRET_KEY|adminPassword|configPassword|adminUser|configUser|MAIL_PASSWORD|APP_KEY|api_key|api_secret|keys|livekit_key|livekit_secret|secret_key|admin_pass|admin_email|mariadbPassword|mariadbRootPassword|privateKey|data|stringData|PASSWD|password|pass|postgresPassword|postgresqlPassword|redminePassword|smtpPassword|registration_shared_secret|shared_secret|secret|admin_token|integrationKey|integration_key|rootPassword|adminPassword|adminUser|adminEmail|emailPassword|secretKey|appId|clientSecret|webhookSecret)$
  version: 3.9.1
