{
 "title": "Draupnir4All Status and logs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Status Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Draupnir Synapse Status",
   "type": "stat",
   "description": "Green means everything is as expected",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(count_over_time({app=\"kube-event-exporter\"} | json | namespace = `matrix` | reason = `Failed` | name =~ `.*draupnir-synapse.*` [5m]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "count_over_time({app=\"kube-event-exporter\"} | json | namespace = `matrix` | reason = `BackOff` | name =~ `.*draupnir-synapse.*` [5m])",
     "legendFormat": "BackOff"
    }
   ]
  },
  {
   "title": "Draupnir4All Status",
   "type": "stat",
   "description": "Green means everything is as expected",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(count_over_time({app=\"kube-event-exporter\"} | json | namespace = `matrix` | reason = `Failed` | name =~ `.*draupnir4all.*` [5m]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "count_over_time({app=\"kube-event-exporter\"} | json | namespace = `matrix` | reason = `BackOff` | name =~ `.*draupnir4all.*` [5m])",
     "legendFormat": "BackOff"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Draupnir4All Synapse Events",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{app=\"kube-event-exporter\"} | json | namespace = `matrix` | name =~ `.*draupnir-synapse.*`"
    }
   ]
  },
  {
   "title": "Draupnir4All Events",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{app=\"kube-event-exporter\"} | json | namespace = `matrix` | name =~ `.*draupnir4all.*`"
    }
   ]
  }
 ]
}