apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: blog
  namespace: flux-system
spec:
  image: registry.midnightthoughts.space/mtrnord/blog
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: blog
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: blog
  filterTags:
    pattern: '^\d{8}-\d{6}$'
  policy:
    alphabetical:
      order: asc
