{
 "title": "DNScollector - Dashboard for Prometheus",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   {
    "name": "stream_id",
    "label": "Stream",
    "query": {
     "query": "label_values({job=\"$job\"},stream_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "DNScollector",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnscollector_exporter_build_info{job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Streams",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(dnscollector_exporter_dnsmessages_total{job=~\"$job\", stream_id=~\"$stream_id\"}) by (stream_id))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (dnscollector_exporter_throughput_ops{job=~\"$job\", stream_id=~\"$stream_id\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Maximum",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (dnscollector_exporter_throughput_ops_max{job=~\"$job\", stream_id=~\"$stream_id\"})",
     "legendFormat": "Maximum"
    }
   ]
  },
  {
   "title": "Total Clients",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (dnscollector_exporter_total_requesters_lru{job=~\"$job\", stream_id=~\"$stream_id\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Total Domains",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (dnscollector_exporter_total_domains_lru{job=~\"$job\", stream_id=~\"$stream_id\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Total Bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (dnscollector_exporter_bytes_total{job=~\"$job\", stream_id=~\"$stream_id\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Packets [rate-5m]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (increase(dnscollector_exporter_dnsmessages_total{job=~\"$job\",stream_id=~\"$stream_id\"}[5m]))",
     "legendFormat": "Pkts [5m] rate"
    }
   ]
  },
  {
   "title": "DNS messages per operations",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (operation) (increase(dnscollector_exporter_operations_total{job=~\"$job\", stream_id=~\"$stream_id\"}[$__range])) != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replies per return code",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (return_code) (increase(dnscollector_exporter_rcodes_total{job=~\"$job\", stream_id=~\"$stream_id\", return_code!=\"-\"}[$__range])) != 0",
     "legendFormat": "{{query_type}}"
    }
   ]
  },
  {
   "title": "Queries per type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (query_type) (increase(dnscollector_exporter_qtypes_total{job=~\"$job\", stream_id=~\"$stream_id\"}[$__range])) != 0",
     "legendFormat": "{{query_type}}"
    }
   ]
  },
  {
   "title": "Transports",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (net_transport) (increase(dnscollector_exporter_ipprotocol_total{job=~\"$job\", stream_id=~\"$stream_id\"}[$__range])) != 0",
     "legendFormat": "{{net_transport}}"
    }
   ]
  },
  {
   "title": "Top Clients [rate-5m] ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(20,sum(rate(dnscollector_exporter_top_requesters{job=~\"$job\", stream_id=~\"$stream_id\"}[5m])) by (ip))",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "IP Protocols",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (net_family) (increase(dnscollector_exporter_ipversion_total{job=~\"$job\", stream_id=~\"$stream_id\", return_code != \"-\"}[$__range])) != 0",
     "legendFormat": "{{net_family}}"
    }
   ]
  },
  {
   "title": "Top",
   "type": "table",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(20, sum by(domain) (increase(dnscollector_exporter_top_noerror_domains{job=~\"$job\", stream_id=~\"$stream_id\"}[$__range]))) != 0"
    },
    {
     "expr": "topk(20, sum by(domain) (increase(dnscollector_exporter_top_nonexistent_domains{job=~\"$job\", stream_id=~\"$stream_id\"}[$__range]))) != 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(20, sum by(domain) (increase(dnscollector_exporter_top_servfail_domains{job=~\"$job\", stream_id=~\"$stream_id\"}[$__range]))) != 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(20, sum by(domain) (increase(dnscollector_exporter_top_suspicious{job=~\"$job\", stream_id=~\"$stream_id\"}[$__range]))) != 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(20, sum by(suffix) (increase(dnscollector_exporter_top_tlds{job=~\"$job\", stream_id=~\"$stream_id\"}[$__range]))) != 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(20, sum by(ip) (increase(dnscollector_exporter_top_requesters{job=~\"$job\", stream_id=~\"$stream_id\"}[$__range]))) != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packet by Qtype [rate-5m]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(dnscollector_exporter_qtypes_total{job=~\"$job\",stream_id=~\"$stream_id\"}[5m])) by (query_type)",
     "legendFormat": "{{ query_type }}"
    }
   ]
  },
  {
   "title": "Packet by Return Code  [rate-5m]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(dnscollector_exporter_rcodes_total{job=~\"$job\", stream_id=~\"$stream_id\", return_code!=\"-\"}[5m])) by ( return_code )",
     "legendFormat": "{{ return_code }}"
    }
   ]
  }
 ]
}