{
 "title": "Stalwart Mailserver Metrics",
 "description": "Simple stalwart metrics dashboard based on the default stalwart metrics endpoint",
 "tags": [
  "prometheus",
  "service",
  "stalwart"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "User Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "stalwart_user_count" }
   ]
  },
  {
   "title": "Domain Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "stalwart_domain_count" }
   ]
  },
  {
   "title": "Auth failed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "stalwart_auth_failed" }
   ]
  },
  {
   "title": "HTTP Active connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stalwart_http_active_connections"
    }
   ]
  },
  {
   "title": "HTTP Connection start",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "stalwart_http_connection_start" }
   ]
  },
  {
   "title": "SMTP Active connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stalwart_smtp_active_connections",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IMAP Active connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stalwart_imap_active_connections",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POP3 Active connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stalwart_pop3_active_connections",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delivery Active connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stalwart_delivery_active_connections",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sieve Active connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stalwart_sieve_active_connections",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Store BLOB Read",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "stalwart_store_blob_read" }
   ]
  },
  {
   "title": "Store Data Write",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "stalwart_store_data_write" }
   ]
  },
  {
   "title": "Store Data Iterate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "stalwart_store_data_iterate" }
   ]
  },
  {
   "title": "HTTP Response body",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "stalwart_http_response_body" }
   ]
  }
 ]
}