apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: external-dns-pdns
    namespace: kube-system
spec:
    releaseName: external-dns-pdns
    chart:
        spec:
            chart: external-dns
            sourceRef:
                kind: HelmRepository
                name: external-dns
    interval: 50m
    values:
        logLevel: debug
        extraArgs:
            - ENC[AES256_GCM,data:UOXZ87TvD01RmCSqZ6Pac4KvdNq1ln0qnLGgn/hCpZFuJ9I7lA==,iv:J/uHmh4xyrJ9f6cRtEUNql6Ex8C1cu8HQHneHTcuvs4=,tag:dnpode3dQ+4XIRJ7VVHkWg==,type:str]
            - ENC[AES256_GCM,data:lT7F/X6foTo5ZzdhKPQc0rlcrUcHcsxVl51Q//uJo7fJisZlOr3Na3C+tek9+iksULvFkSx2zYjKPQZJiJHlCa7iBXlxdaySusroRSOBzA==,iv:9r2919TFgmx3FrtiF/EZLrBRMJz1wJAm57wFCH7JMFI=,tag:ZbhXiyFg05xKuHhMCxS3DQ==,type:str]
            - ENC[AES256_GCM,data:vPqO4wLzPONE4JClRvWuacsGP1axiXMap623h5djoEobq+GFfmNhyk8Jp2CkO1DRBZAy0c/R4Dr+TJlanXSQFn35kpCTZzfMkfO4m+8Z+fn9,iv:uiIoPOctczJUpwQ3LKcQ619IVH4Zz+pOr/QeaO73eVs=,tag:kUJ8KBR/UKeLjCSLZJ7+Cg==,type:str]
            - ENC[AES256_GCM,data:ASXNyXBh1LO8fDfrxAbgIy6aiyFkZ6MrikYk9QsX,iv:mD37PE6/aNpHkSr2TTeOlaapB0V21dtyXjTVK+F2LdA=,tag:aFjkANeTUo7t9wd+swoIjQ==,type:str]
        provider:
            name: pdns
        sources:
            - gateway-httproute
            - gateway-grpcroute
            - gateway-tcproute
            - gateway-tlsroute
            - gateway-udproute
            - pod
            #- service
        rbac:
            additionalPermissions:
                - apiGroups:
                    - ""
                  resources:
                    - namespaces
                  verbs:
                    - get
                    - watch
                    - list
                - apiGroups:
                    - gateway.networking.k8s.io
                  resources:
                    - gateways
                    - httproutes
                    - grpcroutes
                    - tlsroutes
                    - tcproutes
                    - udproutes
                  verbs:
                    - get
                    - watch
                    - list
                - apiGroups:
                    - ""
                  resources:
                    - services
                  verbs:
                    - get
                    - watch
                    - list
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1esjyg2qfy49awv0ptkzvpk425adczjr38m37w2mmcahzc4p8n54sll2nzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaVFoOHkyVWFPT0V3Tjgw
            MlBRcFV2b1A5QS9FSDhVTTEwQTNGajJvalVVCnUrNHNiY2tQc2QzZkRNUFBSeFdu
            djM3VGFWekh5SjViVXM5SjlORlBmMXMKLS0tIFZ1aVhnQWFzRmY2Y3M0blFzaFVx
            Q1ZWT2ZKbFRpSmtKK0JsMXhFWmFFemcKbZ1NrHzpUVE5a7iFJiD09lp1KfqeiYD9
            8HthiyNEv9L2pRqhJgV1/6Id1SnTumTvZIM/b8Y1ak2oPjHrPjc8LA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T08:19:32Z"
    mac: ENC[AES256_GCM,data:wy9i0KWs0mKCNy81bKL4JPwLni7grCYAAG92Lj/kH8qeHr28pORTP5m1kdN3EsQhiY5+WHvbcQVEWWs4F8Qs87KXF9pRpqqQ9ixPtZaQ8xH/vpMLxoTymp9PRIrCdyViEITwniw2bWYoVlpHMMhDjPi3kK51eyZ9Y2iL2aHLZzg=,iv:rJqPbn7gSDBtzmYEeOeftyw96E4QNWyup6e0mQuCjRo=,tag:pe7C7/BhldXoQpc9jwOkSQ==,type:str]
    pgp: []
    encrypted_regex: ^(apiKey|appUserPassword|otelUserPassword|extraArgs|harborAdminPassword|totpVaultKey|kimaiAppSecret|kimaiAdminPassword|GITHUB_CLIENT_ID|GITHUB_CLIENT_SECRET|GITHUB_PRIVATE_KEY|woosh|root_password|rspamd_password|pgdb_password|matrix_access_token|pgdb_remote_url|hmac_secret_key|adminPassword|adminEmail|jenkinsAdminEmail|securityRealm|gerrit.config|routing_key|DATABASE_URL|SMTP_PASSWORD|SECRET_KEY_BASE|admin_password|extraCommands|key|clickhouseDatabaseURL|databaseURL|client_id|client_secret|secret_key_base|otp_secret|private_key|public_key|primaryKey|deterministicKey|keyDerivationSalt|token|clientId|secretKey|installationId|installationKey|uriOverride|adminToken.value|password.value|sql_password|erlangCookie|AUTHENTICATION_PASSWORD|ROOM_API_SECRET_KEY|adminPassword|configPassword|adminUser|configUser|MAIL_PASSWORD|APP_KEY|api_key|api_secret|keys|livekit_key|livekit_secret|secret_key|admin_pass|admin_email|mariadbPassword|mariadbRootPassword|privateKey|data|stringData|PASSWD|password|smtp_auth_password|addresses|smtp_auth_username|authorization_credentials||pass|postgresPassword|postgresqlPassword|redminePassword|smtpPassword|registration_shared_secret|shared_secret|secret|admin_token|integrationKey|integration_key|rootPassword|adminPassword|adminUser|adminEmail|emailPassword|secretKey|appId|clientSecret|webhookSecret|content)$
    version: 3.9.1
