apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: external-dns-pdns
    namespace: kube-system
spec:
    releaseName: external-dns-pdns
    chart:
        spec:
            chart: external-dns
            sourceRef:
                kind: HelmRepository
                name: external-dns
    interval: 50m
    values:
        logLevel: debug
        extraArgs:
            - ENC[AES256_GCM,data:pz71XZwLXatr2jNUOzJbVIGBMp7zCSh/fbHNjQuGAeIcdlxeFw==,iv:5GySG5KwavCzwOCoVwlVfXU9Bq3qITnBcCqdCRhiH1c=,tag:uOTkB9YmCv4gdUr4ThoTQA==,type:str]
            - ENC[AES256_GCM,data:KAG8umTsCCS4r9X+CNf8z/n4iGhUvCNmTujyOwgI8OaNuhYPOfwgN7+UtGJCY+kyggJU6xycy/nR4DsF9MPZOpuTizZBzZUilzP5KAcl1g==,iv:13X8VWIHNdmsF5F5O7xFHYH/9O0ohCCj3hoB2E1Pu/U=,tag:LQIGIHX2ExG4am+bkCW9DQ==,type:str]
            - ENC[AES256_GCM,data:LV7K4tn81zF9krc5z+AZz/jlEDLU2VysVf8U2AO46A==,iv:zqIlNTULF6aEvyOixfnDniF1kpYmkPg2QbbhY/cO3Hk=,tag:jyHC7gkNe0aC6VQ1rlimtw==,type:str]
            - ENC[AES256_GCM,data:yFaT0yKKk/NGqGOTZNh3u5YtxBd3/JcfHDQ/8z26,iv:4uATc3RE60tGjxM0+0rmQm8MSpYs+JUyjLuSoL11WTk=,tag:Q2Qm51OX2ktSeJMvKoX9Dw==,type:str]
        provider:
            name: pdns
        sources:
            - gateway-httproute
            - gateway-grpcroute
            - gateway-tcproute
            - gateway-tlsroute
            - gateway-udproute
            - pod
            #- service
        rbac:
            additionalPermissions:
                - apiGroups:
                    - ""
                  resources:
                    - namespaces
                  verbs:
                    - get
                    - watch
                    - list
                - apiGroups:
                    - gateway.networking.k8s.io
                  resources:
                    - gateways
                    - httproutes
                    - grpcroutes
                    - tlsroutes
                    - tcproutes
                    - udproutes
                  verbs:
                    - get
                    - watch
                    - list
                - apiGroups:
                    - ""
                  resources:
                    - services
                  verbs:
                    - get
                    - watch
                    - list
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1esjyg2qfy49awv0ptkzvpk425adczjr38m37w2mmcahzc4p8n54sll2nzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMmM3eGplWUtMbFJ6L3lP
            MzcvSVV5MEFuOXRpdjJmV1RBUjNuRXgxUVIwClV1ejE2MTFESllaTlFnM2YzU2Fo
            dEVpRHZ6UW9tU2Mwc0RrS2FkUUladTgKLS0tIEpoTEoxTnJZYXdIb1N3eWdLUzA5
            bjczRGdZeno4V29QU0phclZZNDRVbkkKqSW4ultXrdE44iDNmXz2Hy2CxAvaZvvF
            NKHn1c6jOd3+EvuGVdYEfWrVMaHxlA5Ff4rg1KCTKU9xokvir4Olbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T08:05:40Z"
    mac: ENC[AES256_GCM,data:KDnPM1HJ3ATYGVtdQJv6kATj9QE1mopG7muCowX516crsfhQfmuuay0XWLJ/pQt5SI6imJpHhx2GUboqvSZ8Qh1gpu2l3dAde/S7coO1o2kntfZNrsR+QTyOPLYZlVZWUaOjUtKOV38byciIqeY/3fn/XvJDJ7JprNGMP1RCG1o=,iv:JOZ/eGtNT2jybVHYJgByB2mEXkcssaYHTiet1opfBQ8=,tag:APXQ086Q7TyLPsAo3bkswQ==,type:str]
    pgp: []
    encrypted_regex: ^(apiKey|appUserPassword|otelUserPassword|extraArgs|harborAdminPassword|totpVaultKey|kimaiAppSecret|kimaiAdminPassword|GITHUB_CLIENT_ID|GITHUB_CLIENT_SECRET|GITHUB_PRIVATE_KEY|woosh|root_password|rspamd_password|pgdb_password|matrix_access_token|pgdb_remote_url|hmac_secret_key|adminPassword|adminEmail|jenkinsAdminEmail|securityRealm|gerrit.config|routing_key|DATABASE_URL|SMTP_PASSWORD|SECRET_KEY_BASE|admin_password|extraCommands|key|clickhouseDatabaseURL|databaseURL|client_id|client_secret|secret_key_base|otp_secret|private_key|public_key|primaryKey|deterministicKey|keyDerivationSalt|token|clientId|secretKey|installationId|installationKey|uriOverride|adminToken.value|password.value|sql_password|erlangCookie|AUTHENTICATION_PASSWORD|ROOM_API_SECRET_KEY|adminPassword|configPassword|adminUser|configUser|MAIL_PASSWORD|APP_KEY|api_key|api_secret|keys|livekit_key|livekit_secret|secret_key|admin_pass|admin_email|mariadbPassword|mariadbRootPassword|privateKey|data|stringData|PASSWD|password|smtp_auth_password|addresses|smtp_auth_username|authorization_credentials||pass|postgresPassword|postgresqlPassword|redminePassword|smtpPassword|registration_shared_secret|shared_secret|secret|admin_token|integrationKey|integration_key|rootPassword|adminPassword|adminUser|adminEmail|emailPassword|secretKey|appId|clientSecret|webhookSecret|content)$
    version: 3.9.1
