apiVersion: v1
kind: Secret
metadata:
    name: matrix-backup-secret
    namespace: matrix-backup
type: Opaque
stringData:
    mtrnord_password: ENC[AES256_GCM,data:1UWugPLDRWC2,iv:jVIR31haLjgoqhqhodx9AD29OgIAy8A3MB5cm6WVP2Y=,tag:ZWPpxiJrrOXapb7MQNtYug==,type:str]
    mtrnord_ssss_recovery_key: ENC[AES256_GCM,data:ebumKWNNStICm8OT8CijbvWws5gbznbf/3HCjJlBRv1itKzpSUJANvLnw391+YxxYcghdYYZAaQ2qm8=,iv:LXJYjF/Uuk4dxxZYffzU+HSHqM/u2GDlWKEI3w/9nm8=,tag:XVP4p98gu7cp9WvdipQV6w==,type:str]
    lexi_password: ENC[AES256_GCM,data:TOLcQ7bw1QDM,iv:R38xRpWfhtT8jxf0RMynfbsGipOApgz1XTQIYdcg2kk=,tag:lU0SaDRmOtfuRlyasY4UjQ==,type:str]
    lexi_ssss_recovery_key: ENC[AES256_GCM,data:f88XCoUYNao/96mKxQHuvQveUizoV0FURg4iJ7yrdQOtQhPI9raj1xNHza3jN1mvuSu/Y2kriq0cryM=,iv:GW+2c/sQ2X5COcRXxxKFgUmys1QnSEtMXJid1c9ku4E=,tag:0PKUWSIHgGgD5KDfxIMCRA==,type:str]
    s3_access_key: ENC[AES256_GCM,data:2jVHZW/cYXepY2V1fqwGbTB+AI8=,iv:EvlUA2WB7X4+45MXEtgeXlqbOBudZSmXj1XOWQ0uy0Y=,tag:UrVZkYXjEsry+H3jHaxN/w==,type:str]
    s3_secret_key: ENC[AES256_GCM,data:G86JCdmKgQpfG60wjG5b6pG3jQ/gVqpY7sIaapttHnsJqkYg8D6biQ==,iv:4ca7cARSXBbzmc3J28UBbXxiBh7RvNT8jN1ol3e/OFk=,tag:8SrM04aMmdr1i5IlOyu8EA==,type:str]
    key_export_passphrase: ENC[AES256_GCM,data:1xGg/YhrfO/S2mGCgrxOm6uzSUS30s/NGL2dWrivh7kTU7iXQhLmQy703viGqK7XyxNBOycKKsBd2Un47ICc,iv:8milwu03T7UjuLDLYAOkefJ16IF2UM7JJPVbc6jCNGM=,tag:FSTWDOAL8WeBBwmo1eJ24Q==,type:str]
    age_recipients: ENC[AES256_GCM,data:wQqXkhJTlFv47HiKeZipkblw7DsxB0M8ok9J4bb+mSDmtswK0SLM67zoz6ZTsMGx+hpK4ippupI9G/+JNGU=,iv:BM68hlCGy0xZcutM50+iCgRIP7AIxmLQ/1evmu4cM3s=,tag:uNieiriNqJ1u5/Gv0O+p5A==,type:str]
    age_private_key: ENC[AES256_GCM,data:dWyyiEqA+ALVuDYIZiPUnt+rTPWLwussugn5a/arbdEnFTzEBqr3fGhCI9cge/Rh0pUmmO/N50NzBgTnTaoyogLJNPcd/sUkw8Q=,iv:4mUjveSSz4jvTfY/UB4DxvFzqtbngmyfRxr9eNsmptw=,tag:yJYvNN9qHZRWjHWIlOqjwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1esjyg2qfy49awv0ptkzvpk425adczjr38m37w2mmcahzc4p8n54sll2nzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqM0pUaG55UTNobVdCeVdP
            T0cyTUlWRTVFS0l3Y3BmcnFLaVFDSjZqb1gwCjNLVXRDd3BqQ29KdWQxRFArTDlI
            RVhzNVp3c2gzVGMyVXp4NU9zRXRNaEkKLS0tIFRvRVlaVlpLa3lEZ2gyZjFoVWN3
            MnJHNDZhRGRRWHdZVm1sVkljbFh5K0kK4von+bFCRbArOha4jM3hQIuRT20Q1AJL
            FDtgvEvDZlsqMn/MKHDoVw6E4Cqf64R7ulwgxrGE0Xx+KA8sIJ+bWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T09:06:54Z"
    mac: ENC[AES256_GCM,data:kp9cYmG1xH7qsWOFLI6LvzAhjnxxE2MGUGS7NwczER2tkAh7L6WzVm3WHxQznEtHaez65uMRFspLLpkN/H/RETGbVZ6O49egnw+wDDjfOIcr7zdllrkBliaAt+mwJeF/3NYho1nj9axKREn25DeG5PeeRRTSJsZN0BE/8zrcaVU=,iv:EE1TkZDQ/cyAWYa5pBzSYggcSbeYUqmPrjCc4G5kbGM=,tag:RseOCxsH4Ni7EhhJBee0xQ==,type:str]
    pgp: []
    encrypted_regex: ^(apiKey|appUserPassword|otelUserPassword|harborAdminPassword|totpVaultKey|kimaiAppSecret|kimaiAdminPassword|GITHUB_CLIENT_ID|GITHUB_CLIENT_SECRET|GITHUB_PRIVATE_KEY|woosh|root_password|rspamd_password|pgdb_password|matrix_access_token|pgdb_remote_url|hmac_secret_key|adminPassword|adminEmail|jenkinsAdminEmail|securityRealm|gerrit.config|routing_key|DATABASE_URL|SMTP_PASSWORD|SECRET_KEY_BASE|admin_password|extraCommands|key|clickhouseDatabaseURL|databaseURL|client_id|client_secret|secret_key_base|otp_secret|private_key|public_key|primaryKey|deterministicKey|keyDerivationSalt|token|clientId|secretKey|installationId|installationKey|uriOverride|adminToken.value|password.value|sql_password|erlangCookie|AUTHENTICATION_PASSWORD|ROOM_API_SECRET_KEY|adminPassword|configPassword|adminUser|configUser|MAIL_PASSWORD|APP_KEY|api_key|api_secret|keys|livekit_key|livekit_secret|secret_key|admin_pass|admin_email|mariadbPassword|mariadbRootPassword|privateKey|data|stringData|PASSWD|password|pass|postgresPassword|smtp_auth_password|addresses|smtp_auth_username|authorization_credentials|postgresqlPassword|redminePassword|smtpPassword|registration_shared_secret|shared_secret|secret|admin_token|integrationKey|integration_key|rootPassword|adminPassword|adminUser|adminEmail|emailPassword|secretKey|appId|clientSecret|webhookSecret)$
    version: 3.9.1
