apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: buildkitd
  name: buildkitd
  namespace: image-builder
spec:
  serviceName: buildkitd
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: buildkitd
  template:
    metadata:
      labels:
        app: buildkitd
    spec:
      containers:
        - name: buildkitd
          image: moby/buildkit:master
          args:
            - --addr
            - unix:///run/buildkit/buildkitd.sock
            - --addr
            - tcp://0.0.0.0:1234
          ports:
            - containerPort: 1234
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          livenessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          securityContext:
            privileged: true
          volumeMounts:
            - name: docker-config
              mountPath: /root/.docker
              readOnly: true
            - name: containerd-sock
              mountPath: /run/containerd
      volumes:
        - name: docker-config
          secret:
            secretName: image-builder-registry-secret
            items:
              - key: dockerconfig.json
                path: config.json
        - name: containerd-sock
          hostPath:
            path: /run/containerd
            type: Directory
