apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildkitd
  namespace: image-builder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buildkitd
  template:
    metadata:
      labels:
        app: buildkitd
    spec:
      containers:
        - name: buildkitd
          image: moby/buildkit:v0.29.0
          args:
            - --addr
            - unix:///run/buildkit/buildkitd.sock
            - --addr
            - tcp://0.0.0.0:1234
          ports:
            - containerPort: 1234
              protocol: TCP
          securityContext:
            privileged: true
          readinessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          livenessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          volumeMounts:
            - name: docker-config
              mountPath: /root/.docker
              readOnly: true
      volumes:
        - name: docker-config
          secret:
            secretName: image-builder-registry-secret
            items:
              - key: dockerconfig.json
                path: config.json
