apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildkitd-cache
  namespace: image-builder
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hcloud-volumes
  resources:
    requests:
      storage: 20Gi
