apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - buildkitd-pvc.yaml
  - buildkitd-deployment.yaml
  - buildkitd-service.yaml
  - binfmt-daemonset.yaml
  - registry-secret.yaml
  - cosign-secret.yaml
  - build-blog-cronjob.yaml
  - build-continuwuity-cronjob.yaml
  - build-bookwyrm-cronjob.yaml
