apiVersion: v1
kind: Namespace
metadata:
  name: image-builder
  labels:
    # Required for buildkitd (privileged) and binfmt (privileged) pods
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
