apiVersion: v1
kind: Service
metadata:
  name: podman-builder
  namespace: image-builder
spec:
  selector:
    app: podman-builder
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
  type: ClusterIP
