apiVersion: apps/v1
kind: Deployment
metadata:
  name: podman-builder
  namespace: image-builder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podman-builder
  template:
    metadata:
      labels:
        app: podman-builder
    spec:
      serviceAccountName: image-builder
      containers:
        - name: podman
          image: podman:latest
          command:
            - podman
            - system
            - service
            - unix:///run/podman/podman.sock
          ports:
            - containerPort: 8888
              protocol: TCP
          securityContext:
            privileged: true
          volumeMounts:
            - name: docker-config
              mountPath: /root/.docker
              readOnly: true
            - name: podman-sock
              mountPath: /run/podman
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              memory: 2Gi
      volumes:
        - name: docker-config
          secret:
            secretName: image-builder-registry-secret
            items:
              - key: dockerconfig.json
                path: config.json
        - name: podman-sock
          emptyDir: {}
