apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: stalwart-admin
  namespace: stalwart
spec:
  parentRefs:
    - name: email-gateway
      namespace: envoy-gateway
      sectionName: https-stalwart-nordgedanken
    - name: email-gateway
      namespace: envoy-gateway
      sectionName: https-webmail-midnightthoughts
    - name: email-gateway
      namespace: envoy-gateway
      sectionName: https-midnightthoughts-mta-sts
    - name: email-gateway
      namespace: envoy-gateway
      sectionName: https-autoconfig-midnightthoughts
    - name: email-gateway
      namespace: envoy-gateway
      sectionName: https-autodiscover-midnightthoughts
    - name: email-gateway
      namespace: envoy-gateway
      sectionName: https-autoconfig-lists-midnightthoughts
    - name: email-gateway
      namespace: envoy-gateway
      sectionName: https-autodiscover-lists-midnightthoughts
    - name: email-gateway
      namespace: envoy-gateway
      sectionName: https-mta-sts-lists-midnightthoughts
    - name: email-gateway
      namespace: envoy-gateway
      sectionName: https-autoconfig-phorge-mtrnord-blog
    - name: email-gateway
      namespace: envoy-gateway
      sectionName: https-autodiscover-phorge-mtrnord-blog
    - name: email-gateway
      namespace: envoy-gateway
      sectionName: https-mta-sts-phorge-mtrnord-blog
  hostnames:
    - stalwart.nordgedanken.dev
    - webmail.midnightthoughts.space
    - mta-sts.midnightthoughts.space
    - autoconfig.midnightthoughts.space
    - autodiscover.midnightthoughts.space
    - autoconfig.lists.midnightthoughts.space
    - autodiscover.lists.midnightthoughts.space
    - mta-sts.lists.midnightthoughts.space
    - autoconfig.phorge.mtrnord.blog
    - autodiscover.phorge.mtrnord.blog
    - mta-sts.phorge.mtrnord.blog
  rules:
    - backendRefs:
        - name: stalwart-mail
          port: 80
