apiVersion: v1
kind: Secret
metadata:
    name: stalwart-secret
    namespace: stalwart
type: Opaque
stringData:
    pg-user: ENC[AES256_GCM,data:2pQjb+GIRPU=,iv:+xsaXMDdt4YaWTq7JcTnfka3/5WKBzFJJp8PCDDh3EY=,tag:4/hDnbizor+aguoGBavQSA==,type:str]
    pg-password: ENC[AES256_GCM,data:vLcV39f8cggB4Q7sz/YPUVj937fa4fPYJGMv48rtUho90wdnIDSi5EdI1MU3gdSgvgfCa9zy1E03gI9p+EWs,iv:GSXogFiO3s9L7wzMmta+avTinaS0dFXbaGckBCaPaOA=,tag:ZMfxrPRcURA1pNNv61GfNA==,type:str]
    s3-access-key: ENC[AES256_GCM,data:whsSOcpMOH/lWnK4q3xzFvxgve0=,iv:EXsb+ldIcaF5QbS6cGPKPiE2sHTDE4CRgZZk1c4LwJI=,tag:17cyLNU/Ny8C98Uqq/GMtA==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:+HNyNaGLB/SkGoAOuYiNWCLJIJUmYkoJZEdZILyRpAzEoDT3OTF2Tw==,iv:B2STEns5vU1Tcm7gNWV6qli82ilVRpm9+p04kUUOSW4=,tag:xYZp7LgHS74WZaRxOGp4Hg==,type:str]
    ldap-bind-password: ENC[AES256_GCM,data:3E3l2tXW3MSYzUE89CJugfYjJRy0rWq/4IAEU0NJhow0YD2wjuQXs6MS2u2bLu3upR0799Vr4Mhb3UucqRAY,iv:Uq0EkxuKsKxtX2B+Pp78rtf1sN1jscyGyxpUpuofqps=,tag:NVpZG7fq7Zs8bV8TvON/vA==,type:str]
    admin-password: ENC[AES256_GCM,data:/CYbs9+y1zjU,iv:szd62SYYpwKPw8kS/MUOLHTyp4VTdlm5NzW5XGmuKxU=,tag:Vc1mJIJm7cGeVFfIrs4WtA==,type:str]
    metrics-password: ENC[AES256_GCM,data:iXQ/ErlA2v7sJDWzatzkiD37/zT0dAgRTL6cowlpB6MnZ5W6hfWyJgm/M9ZGg/EzZ6fryhBJGLW/f24fIMVp,iv:Ns6+SPI66zgVsP9Icfef5IYs6J/fGrM7LYX6cc88Sdw=,tag:hlRzEnsZ+aCBaur71aOerg==,type:str]
    metrics-username: ENC[AES256_GCM,data:mHWewXiPj7+sVQ==,iv:4+Kr+D7zE22K+eicvkwWBdEJDdl4yHZzYSOJohCniYE=,tag:wf2Ce5myTg6pjvmiLIyNRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1esjyg2qfy49awv0ptkzvpk425adczjr38m37w2mmcahzc4p8n54sll2nzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYms5S2MwUVQ5VUdFVmIy
            Y1VXTUd6SDJHa2VSSHB6WUFGd3JzQW8vZ3hzClZuRnZnNjVtL2dHRTAxS25RMkhG
            aUVpREFNVTBnZmNOd1NWVlQ4RWRldW8KLS0tIFZWeGpzcDdmaGVzQ2lkeERxbjhs
            eFluNVhORFRtWmxvQ0ZldlhZNUpoUWMKdcNA9iJYOGUCc7bDFOIAQ9vnlb68JSTM
            FJmjZvh+vzw7NZpEVQgGkUxZJf0DvvNNOABhhDrSDArbk/89DvZjNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T09:33:44Z"
    mac: ENC[AES256_GCM,data:Hh/BaGYrN/5lPxWn88mseCudmywpxinXntKryTkBNgp0SuVLxO50/j11qgECjgzKOg59nOKFGmQJyImtotweugIPZPfPBdB/4CUCGCgJc7UL+XDAkDd3NpbAV8WHUbalMg78BK//uE7/xHBUapRsoG+9lYXlQm1Yjylh/dsUndg=,iv:YCNyNgQG/hErnq6YM0B50DSyp1cZ/kkjwP2DSe6jpU8=,tag:U8UOTtMxzPKsYhMjizAMrw==,type:str]
    pgp: []
    encrypted_regex: ^(apiKey|appUserPassword|otelUserPassword|harborAdminPassword|totpVaultKey|kimaiAppSecret|kimaiAdminPassword|GITHUB_CLIENT_ID|GITHUB_CLIENT_SECRET|GITHUB_PRIVATE_KEY|woosh|root_password|rspamd_password|pgdb_password|matrix_access_token|pgdb_remote_url|hmac_secret_key|adminPassword|adminEmail|jenkinsAdminEmail|securityRealm|gerrit.config|routing_key|DATABASE_URL|SMTP_PASSWORD|SECRET_KEY_BASE|admin_password|extraCommands|key|clickhouseDatabaseURL|databaseURL|client_id|client_secret|secret_key_base|otp_secret|private_key|public_key|primaryKey|deterministicKey|keyDerivationSalt|token|clientId|secretKey|installationId|installationKey|uriOverride|adminToken.value|password.value|sql_password|erlangCookie|AUTHENTICATION_PASSWORD|ROOM_API_SECRET_KEY|adminPassword|configPassword|adminUser|configUser|MAIL_PASSWORD|APP_KEY|api_key|api_secret|keys|livekit_key|livekit_secret|secret_key|admin_pass|admin_email|mariadbPassword|mariadbRootPassword|privateKey|data|stringData|PASSWD|password|pass|postgresPassword|smtp_auth_password|addresses|smtp_auth_username|authorization_credentials|postgresqlPassword|redminePassword|smtpPassword|registration_shared_secret|shared_secret|secret|admin_token|integrationKey|integration_key|rootPassword|adminPassword|adminUser|adminEmail|emailPassword|secretKey|appId|clientSecret|webhookSecret)$
    version: 3.9.1
