apiVersion: v1
kind: Secret
metadata:
  name: stalwart-secret
  namespace: stalwart
type: Opaque
stringData:
  pg-user: ENC[AES256_GCM,data:2M2yBdjpFII=,iv:ixB2FyyZ28MK+EdpG2FWvlVTauy4XexeAkkMlrHyR2U=,tag:grgnCldASwOyfsagds7Gdg==,type:str]
  pg-password: ENC[AES256_GCM,data:UJJQDB9C/1wZWG6bUb+72to/98IJb+EqevKnwaGfqaw70ZCTEJecrM+qzZpp0XTR1FflKqWc2kbsPEn2AEp3,iv:tUwiB50qe+3h6pVvqgc99pABS/6X6f882fzU4Q1lGyM=,tag:+nXaej6dkCsA0Hp2A8WLpQ==,type:str]
  s3-access-key: ENC[AES256_GCM,data:cBUdiQixXubz6NfEt6HZ15GlYSs=,iv:TKfZRXizjGCQvSETs+kjciaPIbKmL7kxHi+UUadU+Qk=,tag:ZD4cjJOsp73EuKylmrXkGg==,type:str]
  s3-secret-key: ENC[AES256_GCM,data:cwJtv65kgiKdq+qm1QJkjFlZ4xLsQQmAt24NsNqXnQHJz0N4xmQZWw==,iv:7Va/MdKN97W6zEBd9G9Gu1pPThWRyMJJOHfPbL0C0/c=,tag:XCMHXq28SLpxgowMitH+oA==,type:str]
  ldap-bind-password: ENC[AES256_GCM,data:VNJjJPbDAv5MxaHe4I+RplmX8wPX9AjscPaKKGst5qhVq7+kPV5UinYGNfxSAocFYzwKvv7YNb/s1pF1E9y+,iv:KoItQlnlqR4poFXr4sr5UU4PVApxmShS0JpUZWazPdM=,tag:sGFbAoIA0L136Q0IKxvidw==,type:str]
  admin-password: ENC[AES256_GCM,data:X4/ZCinPTvkp,iv:jO8RFUs07EaxL5B80TO+VCDheIotkvSK9OqrgZrp84Y=,tag:bDCuHqaQdKTuOSFFmAewYQ==,type:str]
  metrics-password: ENC[AES256_GCM,data:tIcFtJ6mZENWXUYSltwF2BWfoKXugoPpV+JyeiKXLFQ2x7YYbkyHChrCiEVEPMB6frOgk7JCA0XPo9abB/e/,iv:iEeH3+khjpWf7zB2xxsYv8uqKLYZC339EPlKgRReJ0g=,tag:XZXc9vajrZIsAqEjXS0d9Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1esjyg2qfy49awv0ptkzvpk425adczjr38m37w2mmcahzc4p8n54sll2nzh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuc3Y0OEpEVDFqdWE4QmRw
        eDhMckNITmlQUWlKRHFxczBsdHgzMW5ydTEwCmNJRVhNODE0dVZzZThGUDVKWlp4
        SHVmSEF5TG9Hb1dtc0ladmx0M3BpRGMKLS0tIHBGUkM5Ri9QWFVTeXRhV3N3cGp2
        WGgwdjM0R3ZmUFBkVklCRENuMXZXMEkKMUC9tg/123WhsdCiB5gq/W1LIYPiXo8m
        wwrag1l8VsHDhF8TpKSC0v3/5XY/OomZAUVz03+9kCBIERGTsR24SA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-23T14:10:33Z"
  mac: ENC[AES256_GCM,data:lxWrl7B78axl0rZ/dN9Ioxb4Hy1P6+LmreCmA5305mPUF56nmRFhs0yVH4gEoAoOAa52Nrx3Mzg7QBEE0XrY9Pit8tK5MMxIHqntTmq+7s2BGdvEDg5+vwF+DmkdXfNpAB0TFdLm2W6cjWMeVYo6k++f543C87/Fw81K2A/HEv0=,iv:HkndtOUxrxflkSzqC1QcPR4QWS6vg5spYiy2Vprz3FM=,tag:OmsRhWzxxRfUDsd1aJYgtw==,type:str]
  pgp: []
  encrypted_regex: ^(apiKey|appUserPassword|otelUserPassword|harborAdminPassword|totpVaultKey|kimaiAppSecret|kimaiAdminPassword|GITHUB_CLIENT_ID|GITHUB_CLIENT_SECRET|GITHUB_PRIVATE_KEY|woosh|root_password|rspamd_password|pgdb_password|matrix_access_token|pgdb_remote_url|hmac_secret_key|adminPassword|adminEmail|jenkinsAdminEmail|securityRealm|gerrit.config|routing_key|DATABASE_URL|SMTP_PASSWORD|SECRET_KEY_BASE|admin_password|extraCommands|key|clickhouseDatabaseURL|databaseURL|client_id|client_secret|secret_key_base|otp_secret|private_key|public_key|primaryKey|deterministicKey|keyDerivationSalt|token|clientId|secretKey|installationId|installationKey|uriOverride|adminToken.value|password.value|sql_password|erlangCookie|AUTHENTICATION_PASSWORD|ROOM_API_SECRET_KEY|adminPassword|configPassword|adminUser|configUser|MAIL_PASSWORD|APP_KEY|api_key|api_secret|keys|livekit_key|livekit_secret|secret_key|admin_pass|admin_email|mariadbPassword|mariadbRootPassword|privateKey|data|stringData|PASSWD|password|pass|postgresPassword|smtp_auth_password|addresses|smtp_auth_username|authorization_credentials|postgresqlPassword|redminePassword|smtpPassword|registration_shared_secret|shared_secret|secret|admin_token|integrationKey|integration_key|rootPassword|adminPassword|adminUser|adminEmail|emailPassword|secretKey|appId|clientSecret|webhookSecret)$
  version: 3.9.1
