apiVersion: v1
kind: Secret
metadata:
    name: tlsa-updater-pdns
    namespace: stalwart
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:msqWCCyezDreHnq48zZmenc/8/7HWHdevejJMsXC71aSypUTHO/H9b3zfYequEYPJ/TKixhF+ZLchMAXAC8EVQ==,iv:yF7QLueYaFUbEsrEY0BKfj2ku0uKlfGEDDRLG/3WQWs=,tag:Q+Q7QfvtrKP/6tCakue88w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1esjyg2qfy49awv0ptkzvpk425adczjr38m37w2mmcahzc4p8n54sll2nzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzaWJONkNPVkl0TkhjYUxt
            MGk0aTNrMVlUQXNpTGRLMzgxemVZVE1keWg0ClhLdDhVUEhjZG91RE16OXdGUDhO
            bWFhQzgxQUMzUEVrT2kweWFndzlnUDgKLS0tIEtLZ0NzdE1yQVJ1WUJtclUrS2pM
            VmFiWnlkdDVIdXhUcjhFUldEeWZ6QzAK18qxlygVSItoXDvJG7s2K2lYU8F4p4Wz
            BSn5YmD/Xqj4lUHVCJSk+g2K+oeotvT0e83JbW7mqtoMtL0US0P1Jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T13:14:42Z"
    mac: ENC[AES256_GCM,data:/61x4lFhnCAJAvxHVNTymUAi/IGZCKHgDqkihMYpQ92asIVFG56d0tFn5uzDUctd7J6e/rl7sLuFhuSneJ7cFfdXkuVk9hk/ZaxFbYBwThe+AevxuMGvIrl3GLVfkmJa9oieyLV7L3qOqPvk+c70Bn3tCMIBRPyteDoFSOFXxv0=,iv:M5/NyBv3cWho1avXZlOx/FUJzdNkKDajfvoRTrHO8XE=,tag:svtLye5I15B4y0BWuy1beQ==,type:str]
    pgp: []
    encrypted_regex: ^(apiKey|appUserPassword|otelUserPassword|harborAdminPassword|totpVaultKey|kimaiAppSecret|kimaiAdminPassword|GITHUB_CLIENT_ID|GITHUB_CLIENT_SECRET|GITHUB_PRIVATE_KEY|woosh|root_password|rspamd_password|pgdb_password|matrix_access_token|pgdb_remote_url|hmac_secret_key|adminPassword|adminEmail|jenkinsAdminEmail|securityRealm|gerrit.config|routing_key|DATABASE_URL|SMTP_PASSWORD|SECRET_KEY_BASE|admin_password|extraCommands|key|clickhouseDatabaseURL|databaseURL|client_id|client_secret|secret_key_base|otp_secret|private_key|public_key|primaryKey|deterministicKey|keyDerivationSalt|token|clientId|secretKey|installationId|installationKey|uriOverride|adminToken.value|password.value|sql_password|erlangCookie|AUTHENTICATION_PASSWORD|ROOM_API_SECRET_KEY|adminPassword|configPassword|adminUser|configUser|MAIL_PASSWORD|APP_KEY|api_key|api_secret|keys|livekit_key|livekit_secret|secret_key|admin_pass|admin_email|mariadbPassword|mariadbRootPassword|privateKey|data|stringData|PASSWD|password|pass|postgresPassword|smtp_auth_password|addresses|smtp_auth_username|authorization_credentials|postgresqlPassword|redminePassword|smtpPassword|registration_shared_secret|shared_secret|secret|admin_token|integrationKey|integration_key|rootPassword|adminPassword|adminUser|adminEmail|emailPassword|secretKey|appId|clientSecret|webhookSecret|content)$
    version: 3.9.1
