apiVersion: v1
kind: Namespace
metadata:
    name: postgres-cluster
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1esjyg2qfy49awv0ptkzvpk425adczjr38m37w2mmcahzc4p8n54sll2nzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRenB0bklJcThLUEZDZnZF
            WmYxcHh4K2RMN2dHQXk3MHl2V0g1Q2doVWg4ClZvVmxyUHdrdlo0YXFWbmhoaFlo
            dkVYVkdOY1BIRmFTWnJNTXovSzZhWW8KLS0tIHVzZS9xYmRJdkdvakZ2Z2hTdXFB
            UUREd0xTc21hRmxNT2NGOXhLV0VkYzgKz+4y2imTDL2P9mX/tHp68F1p7cB2syVo
            rn2e1FtzdjfrE+J3uu1CIdQr9CbPqHxw+gxwV6SR46HmMSl53gdShA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T09:47:55Z"
    mac: ENC[AES256_GCM,data:UzKZUAZX/R90aI+jAr42sogaxGEmpbfMPsEpwBtcGDpxpD6/axoohP0nSJOsQ0zJFsmI/TjlW18AKye5MjWEAQ1AHC/YQLL4H0osJDZeUm3qq9Uu59HGn3Wka0UDUkWPqjenPwvX2Jk4uU2T9V13+t7muMLP1UjvN/OTKOwBWRI=,iv:rv7zHndspdlp5bnVSKCpziQJbXDazFWzF6+RALnha14=,tag:I7YZeReQ60cSfnaVhSfDyg==,type:str]
    pgp: []
    encrypted_regex: ^(apiKey|appUserPassword|otelUserPassword|harborAdminPassword|totpVaultKey|kimaiAppSecret|kimaiAdminPassword|GITHUB_CLIENT_ID|GITHUB_CLIENT_SECRET|GITHUB_PRIVATE_KEY|woosh|root_password|rspamd_password|pgdb_password|matrix_access_token|pgdb_remote_url|hmac_secret_key|adminPassword|adminEmail|jenkinsAdminEmail|securityRealm|gerrit.config|routing_key|DATABASE_URL|SMTP_PASSWORD|SECRET_KEY_BASE|admin_password|extraCommands|key|clickhouseDatabaseURL|databaseURL|client_id|client_secret|secret_key_base|otp_secret|private_key|public_key|primaryKey|deterministicKey|keyDerivationSalt|token|clientId|secretKey|installationId|installationKey|uriOverride|adminToken.value|password.value|sql_password|erlangCookie|AUTHENTICATION_PASSWORD|ROOM_API_SECRET_KEY|adminPassword|configPassword|adminUser|configUser|MAIL_PASSWORD|APP_KEY|api_key|api_secret|keys|livekit_key|livekit_secret|secret_key|admin_pass|admin_email|mariadbPassword|mariadbRootPassword|privateKey|data|stringData|PASSWD|password|pass|postgresPassword|postgresqlPassword|redminePassword|smtpPassword|registration_shared_secret|shared_secret|secret|admin_token|integrationKey|integration_key|rootPassword|adminPassword|adminUser|adminEmail|emailPassword|secretKey|appId|clientSecret|webhookSecret)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: pg-s3-credentials
    namespace: postgres-cluster
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:z3ScemPDpbKrWXKmfjTot1szUX0=,iv:Uxr3E0ZXwLqRM1HeA+4p8eI/KG2I1lCv6zI8r4W9lvE=,tag:BMgp+OcI7yjQhObeB34dMg==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:TZ3hP0A9G/0R65ji3kSspL27EQmizOCM1Vgj9ExAf4d25LJ1HxK+BQ==,iv:JNSZFtihQtyg9O3lMqAWHLPSukG957e+4rAyVJxWL3c=,tag:TEHKzTFM+xGd0tF4JFucbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1esjyg2qfy49awv0ptkzvpk425adczjr38m37w2mmcahzc4p8n54sll2nzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRenB0bklJcThLUEZDZnZF
            WmYxcHh4K2RMN2dHQXk3MHl2V0g1Q2doVWg4ClZvVmxyUHdrdlo0YXFWbmhoaFlo
            dkVYVkdOY1BIRmFTWnJNTXovSzZhWW8KLS0tIHVzZS9xYmRJdkdvakZ2Z2hTdXFB
            UUREd0xTc21hRmxNT2NGOXhLV0VkYzgKz+4y2imTDL2P9mX/tHp68F1p7cB2syVo
            rn2e1FtzdjfrE+J3uu1CIdQr9CbPqHxw+gxwV6SR46HmMSl53gdShA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T09:47:55Z"
    mac: ENC[AES256_GCM,data:UzKZUAZX/R90aI+jAr42sogaxGEmpbfMPsEpwBtcGDpxpD6/axoohP0nSJOsQ0zJFsmI/TjlW18AKye5MjWEAQ1AHC/YQLL4H0osJDZeUm3qq9Uu59HGn3Wka0UDUkWPqjenPwvX2Jk4uU2T9V13+t7muMLP1UjvN/OTKOwBWRI=,iv:rv7zHndspdlp5bnVSKCpziQJbXDazFWzF6+RALnha14=,tag:I7YZeReQ60cSfnaVhSfDyg==,type:str]
    pgp: []
    encrypted_regex: ^(apiKey|appUserPassword|otelUserPassword|harborAdminPassword|totpVaultKey|kimaiAppSecret|kimaiAdminPassword|GITHUB_CLIENT_ID|GITHUB_CLIENT_SECRET|GITHUB_PRIVATE_KEY|woosh|root_password|rspamd_password|pgdb_password|matrix_access_token|pgdb_remote_url|hmac_secret_key|adminPassword|adminEmail|jenkinsAdminEmail|securityRealm|gerrit.config|routing_key|DATABASE_URL|SMTP_PASSWORD|SECRET_KEY_BASE|admin_password|extraCommands|key|clickhouseDatabaseURL|databaseURL|client_id|client_secret|secret_key_base|otp_secret|private_key|public_key|primaryKey|deterministicKey|keyDerivationSalt|token|clientId|secretKey|installationId|installationKey|uriOverride|adminToken.value|password.value|sql_password|erlangCookie|AUTHENTICATION_PASSWORD|ROOM_API_SECRET_KEY|adminPassword|configPassword|adminUser|configUser|MAIL_PASSWORD|APP_KEY|api_key|api_secret|keys|livekit_key|livekit_secret|secret_key|admin_pass|admin_email|mariadbPassword|mariadbRootPassword|privateKey|data|stringData|PASSWD|password|pass|postgresPassword|postgresqlPassword|redminePassword|smtpPassword|registration_shared_secret|shared_secret|secret|admin_token|integrationKey|integration_key|rootPassword|adminPassword|adminUser|adminEmail|emailPassword|secretKey|appId|clientSecret|webhookSecret)$
    version: 3.9.1
